Create database ndkm1;

USE [ndkm1]

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE students (
    ma_sv NVARCHAR(50) NOT NULL,
    ten NVARCHAR(100)NOT NULL,
    gioi_tinh NVARCHAR(10),
    ngay_sinh DATE,
    email NVARCHAR(100),
    sdt VARCHAR(20),
    dia_chi NVARCHAR(200),
	CONSTRAINT [PK_students] PRIMARY KEY CLUSTERED 
(
	[ma_sv] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
)ON [PRIMARY]

Go
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE dbo.users (
    user_id NVARCHAR(50) NOT NULL,
	name NVARCHAR(100)NOT NULL,
	gender NVARCHAR(10),
    username NVARCHAR(50) NOT NULL,
    password NVARCHAR(50) NOT NULL,
    role NVARCHAR(50),    
    birthday DATE,
    email NVARCHAR(100),
    phone NVARCHAR(20),  -- Cột số điện thoại
    address NVARCHAR(255),  -- Cột địa chỉ
	CONSTRAINT [PK_users] PRIMARY KEY CLUSTERED 
(
	[user_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

Go
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE studentAccount (
	ID INT IDENTITY(1,1) NOT NULL,
    ma_sv NVARCHAR(50) Not NULL,
    matkhau NVARCHAR(50) Not NULL,
	CONSTRAINT [PK_studentAccount] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

Go
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE attendance (
    idAttendance INT IDENTITY(1,1) NOT NULL,
    ma_sv NVARCHAR(50) NOT NULL,
    ten NVARCHAR(100) NOT NULL,
    attendance_type NVARCHAR(10) NOT NULL,
    timestamp DATETIME DEFAULT GETDATE(),
    face_image VARBINARY(MAX),
	CONSTRAINT [PK_attendance] PRIMARY KEY CLUSTERED 
(
	[idAttendance] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


Go
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE dbo.loginHistory (
    idLogin INT IDENTITY(1,1) NOT NULL,
    user_id NVARCHAR(50) NULL,
	ma_sv NVARCHAR(50) NULL,
    login_time DATETIME,
    success BIT,
	CONSTRAINT [PK_loginHistory] PRIMARY KEY CLUSTERED 
(
	[idLogin] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[studentAccount]  WITH CHECK ADD  CONSTRAINT [FK_studentAccount_students] FOREIGN KEY([ma_sv])
REFERENCES [dbo].[students] ([ma_sv])
GO
ALTER TABLE [dbo].[studentAccount] CHECK CONSTRAINT [FK_studentAccount_students]
GO
GO
ALTER TABLE [dbo].[attendance]  WITH CHECK ADD  CONSTRAINT [FK_attendance_students] FOREIGN KEY([ma_sv])
REFERENCES [dbo].[students] ([ma_sv])
GO
ALTER TABLE [dbo].[attendance] CHECK CONSTRAINT [FK_attendance_students]
GO
GO
ALTER TABLE [dbo].[loginHistory]  WITH CHECK ADD  CONSTRAINT [FK_loginHistory_students] FOREIGN KEY([ma_sv])
REFERENCES [dbo].[students] ([ma_sv])
GO
ALTER TABLE [dbo].[loginHistory] CHECK CONSTRAINT [FK_loginHistory_students]
GO
GO
ALTER TABLE [dbo].[loginHistory]  WITH CHECK ADD  CONSTRAINT [FK_loginHistory_users] FOREIGN KEY([user_id])
REFERENCES [dbo].[users] ([user_id])
GO
ALTER TABLE [dbo].[loginHistory] CHECK CONSTRAINT [FK_loginHistory_users]
GO