# Form implementation generated from reading ui file 'AccountDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import  QDialog,QMessageBox
from DAO_ManageAccount import DAO_Account
from database_connection import DatabaseConnection
import re
class Ui_AccountDialog(object):
    def setupUi(self, AccountDialog):
        AccountDialog.setObjectName("AccountDialog")
        AccountDialog.resize(550, 820)
        AccountDialog.setStyleSheet("QDialog{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit{\n"
"    border: 1px solid gray;\n"
"    border-radius:6px;\n"
"    padding-left:15px;\n"
"    height:30px;\n"
"}\n"
"QDateEdit{\n"
"    border:1px solid gray;\n"
"    border-radius:6px;\n"
"    padding-left:15px;\n"
"    height:28px;\n"
"}\n"
"QComboBox{\n"
"    border:2px solid white;\n"
"    border-radius:8px;\n"
"    padding:1px 15px 1px 3px;\n"
"    background-color: black;\n"
"    color:white;\n"
"    height:25px;\n"
"    padding-left:15px;\n"
"    font-weight:bold;\n"
"    selection-background-color:#298089;\n"
"}\n"
"")
        self.line = QtWidgets.QFrame(parent=AccountDialog)
        self.line.setGeometry(QtCore.QRect(0, 50, 551, 31))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(parent=AccountDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(parent=AccountDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(230, 760, 301, 43))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Add_Account_Button = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.Add_Account_Button.setMinimumSize(QtCore.QSize(0, 41))
        self.Add_Account_Button.setStyleSheet("QPushButton{    \n"
"    background-color: #34D381;\n"
"    border:none;\n"
"    color:white;\n"
"    border-radius:8px;\n"
"    font-weight:bold;\n"
"    font-size:15px;\n"
"}")
        self.Add_Account_Button.setObjectName("Add_Account_Button")
        self.horizontalLayout_2.addWidget(self.Add_Account_Button)
        self.CancelButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.CancelButton.setMinimumSize(QtCore.QSize(0, 41))
        self.CancelButton.setStyleSheet("QPushButton{\n"
"    background-color: #585858;\n"
"    border:none;\n"
"    color:white;\n"
"    border-radius:8px;\n"
"    font-weight:bold;\n"
"    font-size:15px;\n"
"}")
        self.CancelButton.setObjectName("CancelButton")
        self.horizontalLayout_2.addWidget(self.CancelButton)
        self.layoutWidget_2 = QtWidgets.QWidget(parent=AccountDialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 260, 511, 71))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.Username_Account_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget_2)
        self.Username_Account_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.Username_Account_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Username_Account_lineEdit.setFont(font)
        self.Username_Account_lineEdit.setObjectName("Username_Account_lineEdit")
        self.verticalLayout_2.addWidget(self.Username_Account_lineEdit)
        self.layoutWidget_3 = QtWidgets.QWidget(parent=AccountDialog)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 340, 511, 71))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.Password_Account_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget_3)
        self.Password_Account_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.Password_Account_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Password_Account_lineEdit.setFont(font)
        self.Password_Account_lineEdit.setObjectName("Password_Account_lineEdit")
        self.verticalLayout_4.addWidget(self.Password_Account_lineEdit)
        self.layoutWidget1 = QtWidgets.QWidget(parent=AccountDialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(21, 92, 511, 71))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.ID_Manager_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.ID_Manager_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.ID_Manager_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ID_Manager_lineEdit.setFont(font)
        self.ID_Manager_lineEdit.setObjectName("ID_Manager_lineEdit")
        self.verticalLayout.addWidget(self.ID_Manager_lineEdit)
        self.layoutWidget2 = QtWidgets.QWidget(parent=AccountDialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 170, 511, 71))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.Name_Manager_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget2)
        self.Name_Manager_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.Name_Manager_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Name_Manager_lineEdit.setFont(font)
        self.Name_Manager_lineEdit.setObjectName("Name_Manager_lineEdit")
        self.verticalLayout_3.addWidget(self.Name_Manager_lineEdit)
        self.layoutWidget3 = QtWidgets.QWidget(parent=AccountDialog)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 590, 511, 71))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_10 = QtWidgets.QLabel(parent=self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_9.addWidget(self.label_10)
        self.Email_Manager_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget3)
        self.Email_Manager_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.Email_Manager_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Email_Manager_lineEdit.setFont(font)
        self.Email_Manager_lineEdit.setObjectName("Email_Manager_lineEdit")
        self.verticalLayout_9.addWidget(self.Email_Manager_lineEdit)
        self.layoutWidget4 = QtWidgets.QWidget(parent=AccountDialog)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 670, 511, 71))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(parent=self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.Address_Manager_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget4)
        self.Address_Manager_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.Address_Manager_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Address_Manager_lineEdit.setFont(font)
        self.Address_Manager_lineEdit.setObjectName("Address_Manager_lineEdit")
        self.verticalLayout_5.addWidget(self.Address_Manager_lineEdit)
        self.layoutWidget5 = QtWidgets.QWidget(parent=AccountDialog)
        self.layoutWidget5.setGeometry(QtCore.QRect(20, 510, 511, 71))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_9 = QtWidgets.QLabel(parent=self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9)
        self.Phone_Manager_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget5)
        self.Phone_Manager_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.Phone_Manager_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Phone_Manager_lineEdit.setFont(font)
        self.Phone_Manager_lineEdit.setObjectName("Phone_Manager_lineEdit")
        self.verticalLayout_8.addWidget(self.Phone_Manager_lineEdit)
        self.layoutWidget6 = QtWidgets.QWidget(parent=AccountDialog)
        self.layoutWidget6.setGeometry(QtCore.QRect(20, 430, 511, 60))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(parent=self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.Role_Account_comboBox = QtWidgets.QComboBox(parent=self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Role_Account_comboBox.setFont(font)
        self.Role_Account_comboBox.setObjectName("Role_Account_comboBox")
        self.Role_Account_comboBox.addItem("")
        self.Role_Account_comboBox.addItem("")
        self.verticalLayout_6.addWidget(self.Role_Account_comboBox)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_11 = QtWidgets.QLabel(parent=self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_10.addWidget(self.label_11)
        self.Gender_Manager_comboBox = QtWidgets.QComboBox(parent=self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Gender_Manager_comboBox.setFont(font)
        self.Gender_Manager_comboBox.setObjectName("Gender_Manager_comboBox")
        self.Gender_Manager_comboBox.addItem("")
        self.Gender_Manager_comboBox.addItem("")
        self.verticalLayout_10.addWidget(self.Gender_Manager_comboBox)
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(parent=self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.Birth_Manage_dateEdit = QtWidgets.QDateEdit(parent=self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Birth_Manage_dateEdit.setFont(font)
        self.Birth_Manage_dateEdit.setObjectName("Birth_Manage_dateEdit")
        self.verticalLayout_7.addWidget(self.Birth_Manage_dateEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_7)

        self.retranslateUi(AccountDialog)
        QtCore.QMetaObject.connectSlotsByName(AccountDialog)

    def retranslateUi(self, AccountDialog):
        _translate = QtCore.QCoreApplication.translate
        AccountDialog.setWindowTitle(_translate("AccountDialog", "Dialog"))
        self.label.setText(_translate("AccountDialog", "Add New Account"))
        self.Add_Account_Button.setText(_translate("AccountDialog", "Add Account"))
        self.CancelButton.setText(_translate("AccountDialog", "Cancel"))
        self.label_3.setText(_translate("AccountDialog", "Username"))
        self.label_5.setText(_translate("AccountDialog", "Password"))
        self.label_2.setText(_translate("AccountDialog", "ID Manager"))
        self.label_4.setText(_translate("AccountDialog", "Full Name"))
        self.label_10.setText(_translate("AccountDialog", "Email"))
        self.label_6.setText(_translate("AccountDialog", "Address"))
        self.label_9.setText(_translate("AccountDialog", "Phone Number"))
        self.label_7.setText(_translate("AccountDialog", "Role"))
        self.Role_Account_comboBox.setItemText(0, _translate("AccountDialog", "quanly"))
        self.Role_Account_comboBox.setItemText(1, _translate("AccountDialog", "admin"))
        self.label_11.setText(_translate("AccountDialog", "Gender"))
        self.Gender_Manager_comboBox.setItemText(0, _translate("AccountDialog", "Male"))
        self.Gender_Manager_comboBox.setItemText(1, _translate("AccountDialog", "Female"))
        self.label_8.setText(_translate("AccountDialog", "Date of Birth"))


class AccountDialog(QDialog, Ui_AccountDialog):
        def __init__(self, parent=None, connection=None):
                super().__init__(parent)
                self.setupUi(self)
                self.db = connection  # Sử dụng kết nối được truyền vào
                self.dao_manager = DAO_Account(self.db)  # Khởi tạo DAO với kết nối cơ sở dữ liệu
                self.Add_Account_Button.clicked.connect(self.them_account_gui)
                self.CancelButton.clicked.connect(self.reject)

                self.patterns = {
                'user_id': r'^\d{8}$',  # Ví dụ: 12345678
                'ten': r'^([A-ZÀ-Ỹ][a-zà-ỹ]+)(?:\s[A-ZÀ-Ỹ][a-zà-ỹ]+)*$',  # Ví dụ: Nguyễn Văn A
                'email': r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$',  # Ví dụ: email@example.com
                'sdt': r'^0\d{9}$',  # Ví dụ: 0123456789
                'dia_chi': r'^[A-Za-z0-9À-ỹ\s,.-/]{5,100}$r',  # Ví dụ: 123 Đường ABC                        
                'username': r'^\S{6,}$',   # Không chứa khoảng trắng, lớn hơn 5 ký tự
                'password': r'^.{5,20}$'        
                }
                
        def them_account_gui(self):
                ma_id = self.ID_Manager_lineEdit.text()
                ten = self.Name_Manager_lineEdit.text()
                username = self.Username_Account_lineEdit.text()
                password = self.Password_Account_lineEdit.text()
                role = self.Role_Account_comboBox.currentText()
                gioi_tinh = self.Gender_Manager_comboBox.currentText()
                ngay_sinh = self.Birth_Manage_dateEdit.date().toString("yyyy-MM-dd")
                sdt = self.Phone_Manager_lineEdit.text()
                email = self.Email_Manager_lineEdit.text()
                dia_chi = self.Address_Manager_lineEdit.text()
                
                
        # Validate inputs
                if not ma_id or not ten or not username or not password:
                        QMessageBox.warning(self, "Lỗi nhập liệu", "Mã Quản lí, tên, Username và password không được để trống!")
                        return

                        # Kiểm tra định dạng các trường bắt buộc
                if not re.match(self.patterns['user_id'], ma_id):
                        QMessageBox.warning(self, "Lỗi nhập liệu", "Mã Quản lí không hợp lệ! (Phải gồm 8 số, ví dụ: 12345678)")
                        return

                if not re.match(self.patterns['ten'], ten):
                        QMessageBox.warning(self, "Lỗi nhập liệu", "Tên Quản lí không hợp lệ! (Ví dụ: Nguyễn Văn An)")
                        return

                if not re.match(self.patterns['username'], username):
                        QMessageBox.warning(self, "Lỗi nhập liệu", "Username không hợp lệ! Username nhiều hơn 5 kí tự (Ví dụ: email@example.com)")
                        return
                
                if not re.match(self.patterns['password'], password):
                        QMessageBox.warning(self, "Lỗi nhập liệu", "Password không hợp lệ! Password Từ 5-20 kí tự (Ví dụ: email@example.com)")
                        return
                
                # Kiểm tra các trường tùy chọn nếu người dùng nhập liệu
                if email and not re.match(self.patterns['email'], email):
                        QMessageBox.warning(self, "Lỗi nhập liệu", "Email không hợp lệ! (Ví dụ: email@example.com)")
                        return

                if sdt and not re.match(self.patterns['sdt'], sdt):
                        QMessageBox.warning(self, "Lỗi nhập liệu", "Số điện thoại không hợp lệ! (Phải có 10 chữ số, ví dụ: 0123456789)")
                        return

                if dia_chi and not re.match(self.patterns['dia_chi'], dia_chi):
                        QMessageBox.warning(self, "Lỗi nhập liệu", "Địa chỉ không hợp lệ! (Chỉ gồm chữ và số, từ 5 đến 100 ký tự)")
                        return

                try:
                        if self.dao_manager.them_account(ma_id, ten, username, password, role, gioi_tinh, ngay_sinh, email, sdt, dia_chi):
                                QMessageBox.information(self, "Thành công", "Tài khoản Quản lí đã được thêm thành công!")
                                self.accept()  # Đóng hộp thoại nếu thêm thành công
                        else:
                                QMessageBox.warning(self, "Lỗi", "Mã Quản lí đã tồn tại! Vui lòng nhập mã khác.")
                except Exception as e:
                        print(f"Lỗi khi thêm tài khoản: {e}")
                        QMessageBox.critical(self, "Lỗi cơ sở dữ liệu", "Đã xảy ra lỗi khi thêm Quản lí. Vui lòng thử lại!")


