# Form implementation generated from reading ui file 'StudentDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import  QDialog,QMessageBox
from SaveImg import UI_SaveImg
from DAO_QLSV import DAO_SinhVien
from database_connection import DatabaseConnection
import re
class Ui_StudentDialog(object):
        def setupUi(self, StudentDialog):
                StudentDialog.setObjectName("StudentDialog")
                StudentDialog.resize(550, 620)
                StudentDialog.setStyleSheet("QDialog{\n"
                "    background-color: rgb(255, 255, 255);\n"
                "}\n"
                "QLineEdit{\n"
                "    border: 1px solid gray;\n"
                "    border-radius:6px;\n"
                "    padding-left:15px;\n"
                "    height:30px;\n"
                "}\n"
                "QDateEdit{\n"
                "    border:1px solid gray;\n"
                "    border-radius:6px;\n"
                "    padding-left:15px;\n"
                "    height:28px;\n"
                "}\n"
                "QComboBox{\n"
                "    border:2px solid white;\n"
                "    border-radius:8px;\n"
                "    padding:1px 15px 1px 3px;\n"
                "    background-color: black;\n"
                "    color:white;\n"
                "    height:25px;\n"
                "    padding-left:15px;\n"
                "    font-weight:bold;\n"
                "    selection-background-color:#298089;\n"
                "}\n"
                "")
                self.line = QtWidgets.QFrame(parent=StudentDialog)
                self.line.setGeometry(QtCore.QRect(0, 50, 551, 31))
                self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
                self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
                self.line.setObjectName("line")
                self.label = QtWidgets.QLabel(parent=StudentDialog)
                self.label.setGeometry(QtCore.QRect(10, 10, 251, 31))
                font = QtGui.QFont()
                font.setFamily("Rockwell")
                font.setPointSize(20)
                font.setBold(True)
                font.setWeight(75)
                self.label.setFont(font)
                self.label.setObjectName("label")
                self.layoutWidget = QtWidgets.QWidget(parent=StudentDialog)
                self.layoutWidget.setGeometry(QtCore.QRect(20, 91, 511, 451))
                self.layoutWidget.setObjectName("layoutWidget")
                self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
                self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout_2.setObjectName("verticalLayout_2")
                self.verticalLayout = QtWidgets.QVBoxLayout()
                self.verticalLayout.setObjectName("verticalLayout")
                self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
                font = QtGui.QFont()
                font.setPointSize(12)
                self.label_2.setFont(font)
                self.label_2.setObjectName("label_2")
                self.verticalLayout.addWidget(self.label_2)
                self.ID_Student_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
                self.ID_Student_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
                self.ID_Student_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.ID_Student_lineEdit.setFont(font)
                self.ID_Student_lineEdit.setObjectName("ID_Student_lineEdit")
                self.verticalLayout.addWidget(self.ID_Student_lineEdit)
                self.verticalLayout_2.addLayout(self.verticalLayout)
                self.verticalLayout_3 = QtWidgets.QVBoxLayout()
                self.verticalLayout_3.setObjectName("verticalLayout_3")
                self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget)
                font = QtGui.QFont()
                font.setPointSize(12)
                self.label_4.setFont(font)
                self.label_4.setObjectName("label_4")
                self.verticalLayout_3.addWidget(self.label_4)
                self.Name_Student_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
                self.Name_Student_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
                self.Name_Student_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.Name_Student_lineEdit.setFont(font)
                self.Name_Student_lineEdit.setObjectName("Name_Student_lineEdit")
                self.verticalLayout_3.addWidget(self.Name_Student_lineEdit)
                self.verticalLayout_2.addLayout(self.verticalLayout_3)
                self.horizontalLayout = QtWidgets.QHBoxLayout()
                self.horizontalLayout.setObjectName("horizontalLayout")
                self.verticalLayout_6 = QtWidgets.QVBoxLayout()
                self.verticalLayout_6.setObjectName("verticalLayout_6")
                self.label_7 = QtWidgets.QLabel(parent=self.layoutWidget)
                font = QtGui.QFont()
                font.setPointSize(12)
                self.label_7.setFont(font)
                self.label_7.setObjectName("label_7")
                self.verticalLayout_6.addWidget(self.label_7)
                self.Gender_Student_comboBox = QtWidgets.QComboBox(parent=self.layoutWidget)
                font = QtGui.QFont()
                font.setPointSize(12)
                font.setBold(True)
                font.setWeight(75)
                self.Gender_Student_comboBox.setFont(font)
                self.Gender_Student_comboBox.setObjectName("Gender_Student_comboBox")
                self.Gender_Student_comboBox.addItem("")
                self.Gender_Student_comboBox.addItem("")
                self.verticalLayout_6.addWidget(self.Gender_Student_comboBox)
                self.horizontalLayout.addLayout(self.verticalLayout_6)
                self.verticalLayout_7 = QtWidgets.QVBoxLayout()
                self.verticalLayout_7.setObjectName("verticalLayout_7")
                self.label_8 = QtWidgets.QLabel(parent=self.layoutWidget)
                font = QtGui.QFont()
                font.setPointSize(12)
                self.label_8.setFont(font)
                self.label_8.setObjectName("label_8")
                self.verticalLayout_7.addWidget(self.label_8)
                self.Birth_Student_dateEdit = QtWidgets.QDateEdit(parent=self.layoutWidget)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.Birth_Student_dateEdit.setFont(font)
                self.Birth_Student_dateEdit.setObjectName("Birth_Student_dateEdit")
                self.verticalLayout_7.addWidget(self.Birth_Student_dateEdit)
                self.horizontalLayout.addLayout(self.verticalLayout_7)
                self.verticalLayout_2.addLayout(self.horizontalLayout)
                self.verticalLayout_8 = QtWidgets.QVBoxLayout()
                self.verticalLayout_8.setObjectName("verticalLayout_8")
                self.label_9 = QtWidgets.QLabel(parent=self.layoutWidget)
                font = QtGui.QFont()
                font.setPointSize(12)
                self.label_9.setFont(font)
                self.label_9.setObjectName("label_9")
                self.verticalLayout_8.addWidget(self.label_9)
                self.Phone_Student_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
                self.Phone_Student_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
                self.Phone_Student_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.Phone_Student_lineEdit.setFont(font)
                self.Phone_Student_lineEdit.setObjectName("Phone_Student_lineEdit")
                self.verticalLayout_8.addWidget(self.Phone_Student_lineEdit)
                self.verticalLayout_2.addLayout(self.verticalLayout_8)
                self.verticalLayout_9 = QtWidgets.QVBoxLayout()
                self.verticalLayout_9.setObjectName("verticalLayout_9")
                self.label_10 = QtWidgets.QLabel(parent=self.layoutWidget)
                font = QtGui.QFont()
                font.setPointSize(12)
                self.label_10.setFont(font)
                self.label_10.setObjectName("label_10")
                self.verticalLayout_9.addWidget(self.label_10)
                self.Email_Student_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
                self.Email_Student_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
                self.Email_Student_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.Email_Student_lineEdit.setFont(font)
                self.Email_Student_lineEdit.setObjectName("Email_Student_lineEdit")
                self.verticalLayout_9.addWidget(self.Email_Student_lineEdit)
                self.verticalLayout_2.addLayout(self.verticalLayout_9)
                self.verticalLayout_5 = QtWidgets.QVBoxLayout()
                self.verticalLayout_5.setObjectName("verticalLayout_5")
                self.label_6 = QtWidgets.QLabel(parent=self.layoutWidget)
                font = QtGui.QFont()
                font.setPointSize(12)
                self.label_6.setFont(font)
                self.label_6.setObjectName("label_6")
                self.verticalLayout_5.addWidget(self.label_6)
                self.Address_Student_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
                self.Address_Student_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
                self.Address_Student_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.Address_Student_lineEdit.setFont(font)
                self.Address_Student_lineEdit.setObjectName("Address_Student_lineEdit")
                self.verticalLayout_5.addWidget(self.Address_Student_lineEdit)
                self.verticalLayout_2.addLayout(self.verticalLayout_5)
                self.layoutWidget1 = QtWidgets.QWidget(parent=StudentDialog)
                self.layoutWidget1.setGeometry(QtCore.QRect(221, 560, 301, 43))
                self.layoutWidget1.setObjectName("layoutWidget1")
                self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
                self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_2.setObjectName("horizontalLayout_2")
                self.Add_Student_Button = QtWidgets.QPushButton(parent=self.layoutWidget1)
                self.Add_Student_Button.setMinimumSize(QtCore.QSize(0, 41))
                self.Add_Student_Button.setStyleSheet("QPushButton{    \n"
                "    background-color: #34D381;\n"
                "    border:none;\n"
                "    color:white;\n"
                "    border-radius:8px;\n"
                "    font-weight:bold;\n"
                "    font-size:15px;\n"
                "}")
                self.Add_Student_Button.setObjectName("Add_Student_Button")
                self.horizontalLayout_2.addWidget(self.Add_Student_Button)
                self.SaveImage_Student_Button = QtWidgets.QPushButton(parent=self.layoutWidget1)
                self.SaveImage_Student_Button.setMinimumSize(QtCore.QSize(0, 41))
                self.SaveImage_Student_Button.setStyleSheet("QPushButton{    \n"
                "    background-color: rgb(255, 85, 0);\n"
                "    border:none;\n"
                "    color:white;\n"
                "    border-radius:8px;\n"
                "    font-weight:bold;\n"
                "    font-size:15px;\n"
                "}")
                self.SaveImage_Student_Button.setObjectName("SaveImage_Student_Button")
                self.horizontalLayout_2.addWidget(self.SaveImage_Student_Button)
                self.CancelButton = QtWidgets.QPushButton(parent=self.layoutWidget1)
                self.CancelButton.setMinimumSize(QtCore.QSize(0, 41))
                self.CancelButton.setStyleSheet("QPushButton{\n"
                "    background-color: #585858;\n"
                "    border:none;\n"
                "    color:white;\n"
                "    border-radius:8px;\n"
                "    font-weight:bold;\n"
                "    font-size:15px;\n"
                "}")
                self.CancelButton.setObjectName("CancelButton")
                self.horizontalLayout_2.addWidget(self.CancelButton)

                self.retranslateUi(StudentDialog)
                QtCore.QMetaObject.connectSlotsByName(StudentDialog)

        def retranslateUi(self, StudentDialog):
                _translate = QtCore.QCoreApplication.translate
                StudentDialog.setWindowTitle(_translate("StudentDialog", "Dialog"))
                self.label.setText(_translate("StudentDialog", "Add New Student"))
                self.label_2.setText(_translate("StudentDialog", "ID Student"))
                self.label_4.setText(_translate("StudentDialog", "Full Name"))
                self.label_7.setText(_translate("StudentDialog", "Gender"))
                self.Gender_Student_comboBox.setItemText(0, _translate("StudentDialog", "Male"))
                self.Gender_Student_comboBox.setItemText(1, _translate("StudentDialog", "Female"))
                self.label_8.setText(_translate("StudentDialog", "Date of Birth"))
                self.label_9.setText(_translate("StudentDialog", "Phone Number"))
                self.label_10.setText(_translate("StudentDialog", "Email"))
                self.label_6.setText(_translate("StudentDialog", "Address"))
                self.Add_Student_Button.setText(_translate("StudentDialog", "Add Student"))
                self.SaveImage_Student_Button.setText(_translate("StudentDialog", "Save Image"))
                self.CancelButton.setText(_translate("StudentDialog", "Cancel"))
                
        
class StudentDialog(QDialog, Ui_StudentDialog):
    def __init__(self, parent=None, connection=None):
        super().__init__(parent)
        self.setupUi(self)
        self.db = connection
        self.dao_sinh_vien = DAO_SinhVien(self.db)
        self.Add_Student_Button.clicked.connect(self.them_sinh_vien_gui)
        self.SaveImage_Student_Button.clicked.connect(self.open_SaveImg_dialog)
        self.CancelButton.clicked.connect(self.reject)

        # Define regex patterns
        self.patterns = {
            'ma_sv': r'^\d{8}$',  # Ví dụ: 12345678
            'ten': r'^([A-ZÀ-Ỹ][a-zà-ỹ]+)(?:\s[A-ZÀ-Ỹ][a-zà-ỹ]+)*$',  # Ví dụ: Nguyễn Văn A
            'email': r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$',  # Ví dụ: email@example.com
            'sdt': r'^0\d{9}$',  # Ví dụ: 0123456789
            'dia_chi': r'^[A-Za-z0-9À-ỹ\s,.-/]{5,100}$r'  # Ví dụ: 123 Đường ABC
        }

    def them_sinh_vien_gui(self):
        ma_sv = self.ID_Student_lineEdit.text()
        ten = self.Name_Student_lineEdit.text()
        gioi_tinh = self.Gender_Student_comboBox.currentText()
        ngay_sinh = self.Birth_Student_dateEdit.date().toString("yyyy-MM-dd")
        email = self.Email_Student_lineEdit.text()
        sdt = self.Phone_Student_lineEdit.text()
        dia_chi = self.Address_Student_lineEdit.text()

        # Validate inputs
        if not ma_sv or not ten:
            QMessageBox.warning(self, "Lỗi nhập liệu", "Mã sinh viên và tên không được để trống!")
            return

        # Kiểm tra định dạng các trường bắt buộc
        if not re.match(self.patterns['ma_sv'], ma_sv):
            QMessageBox.warning(self, "Lỗi nhập liệu", "Mã sinh viên không hợp lệ! (Phải gồm 8 số, ví dụ: 12345678)")
            return

        if not re.match(self.patterns['ten'], ten):
            QMessageBox.warning(self, "Lỗi nhập liệu", "Tên sinh viên không hợp lệ! (Ví dụ: Nguyễn Văn An)")
            return

        # Kiểm tra các trường tùy chọn nếu người dùng nhập liệu
        if email and not re.match(self.patterns['email'], email):
            QMessageBox.warning(self, "Lỗi nhập liệu", "Email không hợp lệ! (Ví dụ: email@example.com)")
            return

        if sdt and not re.match(self.patterns['sdt'], sdt):
            QMessageBox.warning(self, "Lỗi nhập liệu", "Số điện thoại không hợp lệ! (Phải có 10 chữ số, ví dụ: 0123456789)")
            return

        if dia_chi and not re.match(self.patterns['dia_chi'], dia_chi):
            QMessageBox.warning(self, "Lỗi nhập liệu", "Địa chỉ không hợp lệ! (Chỉ gồm chữ và số, từ 5 đến 100 ký tự)")
            return

        # Thêm sinh viên vào cơ sở dữ liệu
        try:
            if self.dao_sinh_vien.them_sinh_vien(ma_sv, ten, gioi_tinh, ngay_sinh, email, sdt, dia_chi):
                QMessageBox.information(self, "Thành công", "Sinh viên đã được thêm thành công!")
                self.accept()  # Đóng hộp thoại nếu thêm thành công
            else:
                QMessageBox.warning(self, "Lỗi", "Mã sinh viên đã tồn tại! Vui lòng nhập mã khác.")
        except Exception as e:
            print(f"Lỗi khi thêm sinh viên: {e}")
            QMessageBox.critical(self, "Lỗi cơ sở dữ liệu", "Đã xảy ra lỗi khi thêm sinh viên. Vui lòng thử lại!")

    def open_SaveImg_dialog(self):
        save_img_ui = UI_SaveImg()
        result = save_img_ui.exec()
        if result == QDialog.DialogCode.Accepted:
            pass  # Handle image saving if needed