# Form implementation generated from reading ui file 'StudentWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 880)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(110, 10, 1061, 261))
        self.groupBox.setStyleSheet("QLineEdit{\n"
"    border: 1px solid gray;\n"
"    border-radius:6px;\n"
"    padding-left:15px;\n"
"    height:30px;\n"
"}\n"
"QDateEdit{\n"
"    border:1px solid gray;\n"
"    border-radius:6px;\n"
"    padding-left:15px;\n"
"    height:28px;\n"
"}\n"
"QDateTimeEdit{\n"
"    border:1px solid gray;\n"
"    border-radius:6px;\n"
"    padding-left:15px;\n"
"    height:28px;\n"
"}\n"
"QComboBox{\n"
"    border:2px solid white;\n"
"    border-radius:8px;\n"
"    padding:1px 15px 1px 3px;\n"
"    background-color: black;\n"
"    color:white;\n"
"    height:25px;\n"
"    padding-left:15px;\n"
"    font-weight:bold;\n"
"    selection-background-color:#298089;\n"
"}\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(parent=self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(370, 30, 441, 59))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_9 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_13.addWidget(self.label_9)
        self.Name_Student_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.Name_Student_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.Name_Student_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Name_Student_lineEdit.setFont(font)
        self.Name_Student_lineEdit.setObjectName("Name_Student_lineEdit")
        self.verticalLayout_13.addWidget(self.Name_Student_lineEdit)
        self.layoutWidget_2 = QtWidgets.QWidget(parent=self.groupBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 110, 341, 59))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_15 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_16.addWidget(self.label_15)
        self.Phone_Student_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget_2)
        self.Phone_Student_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.Phone_Student_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Phone_Student_lineEdit.setFont(font)
        self.Phone_Student_lineEdit.setObjectName("Phone_Student_lineEdit")
        self.verticalLayout_16.addWidget(self.Phone_Student_lineEdit)
        self.layoutWidget_3 = QtWidgets.QWidget(parent=self.groupBox)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 30, 341, 59))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_8 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_12.addWidget(self.label_8)
        self.ID_Student_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget_3)
        self.ID_Student_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.ID_Student_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ID_Student_lineEdit.setFont(font)
        self.ID_Student_lineEdit.setObjectName("ID_Student_lineEdit")
        self.verticalLayout_12.addWidget(self.ID_Student_lineEdit)
        self.layoutWidget_5 = QtWidgets.QWidget(parent=self.groupBox)
        self.layoutWidget_5.setGeometry(QtCore.QRect(400, 110, 401, 59))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_17 = QtWidgets.QLabel(parent=self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_18.addWidget(self.label_17)
        self.Email_Student_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget_5)
        self.Email_Student_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.Email_Student_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Email_Student_lineEdit.setFont(font)
        self.Email_Student_lineEdit.setObjectName("Email_Student_lineEdit")
        self.verticalLayout_18.addWidget(self.Email_Student_lineEdit)
        self.layoutWidget_4 = QtWidgets.QWidget(parent=self.groupBox)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 180, 451, 59))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_18 = QtWidgets.QLabel(parent=self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_19.addWidget(self.label_18)
        self.Address_Student_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget_4)
        self.Address_Student_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.Address_Student_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Address_Student_lineEdit.setFont(font)
        self.Address_Student_lineEdit.setObjectName("Address_Student_lineEdit")
        self.verticalLayout_19.addWidget(self.Address_Student_lineEdit)
        self.layoutWidget_6 = QtWidgets.QWidget(parent=self.groupBox)
        self.layoutWidget_6.setGeometry(QtCore.QRect(830, 110, 181, 61))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_14 = QtWidgets.QLabel(parent=self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_15.addWidget(self.label_14)
        self.Birth_Student_dateEdit = QtWidgets.QDateEdit(parent=self.layoutWidget_6)
        self.Birth_Student_dateEdit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Birth_Student_dateEdit.setFont(font)
        self.Birth_Student_dateEdit.setObjectName("Birth_Student_dateEdit")
        self.verticalLayout_15.addWidget(self.Birth_Student_dateEdit)
        self.layoutWidget_7 = QtWidgets.QWidget(parent=self.groupBox)
        self.layoutWidget_7.setGeometry(QtCore.QRect(830, 30, 181, 59))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_16 = QtWidgets.QLabel(parent=self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_17.addWidget(self.label_16)
        self.Gender_Student_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget_7)
        self.Gender_Student_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.Gender_Student_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Gender_Student_lineEdit.setFont(font)
        self.Gender_Student_lineEdit.setObjectName("Gender_Student_lineEdit")
        self.verticalLayout_17.addWidget(self.Gender_Student_lineEdit)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 290, 1251, 581))
        self.widget.setObjectName("widget")
        self.StudentInfo_Table = QtWidgets.QTableWidget(parent=self.widget)
        self.StudentInfo_Table.setGeometry(QtCore.QRect(10, 10, 1231, 561))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.StudentInfo_Table.setFont(font)
        self.StudentInfo_Table.setStyleSheet("QHeaderView::section{\n"
"    font-weight:bold;\n"
"    background-color:black;\n"
"    color:white;\n"
"}\n"
"QTableWidget{    \n"
"    alternate-background-color: #B0BDFB;\n"
"    background-color:#F4F9FA;\n"
"}")
        self.StudentInfo_Table.setAlternatingRowColors(True)
        self.StudentInfo_Table.setObjectName("StudentInfo_Table")
        self.StudentInfo_Table.setColumnCount(9)
        self.StudentInfo_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.StudentInfo_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentInfo_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentInfo_Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentInfo_Table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentInfo_Table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentInfo_Table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentInfo_Table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentInfo_Table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentInfo_Table.setHorizontalHeaderItem(8, item)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Thông tin Sinh Viên"))
        self.label_9.setText(_translate("MainWindow", "Full Name"))
        self.label_15.setText(_translate("MainWindow", "Phone Number"))
        self.label_8.setText(_translate("MainWindow", "ID Student"))
        self.label_17.setText(_translate("MainWindow", "Email"))
        self.label_18.setText(_translate("MainWindow", "Address"))
        self.label_14.setText(_translate("MainWindow", "Date of Birth"))
        self.label_16.setText(_translate("MainWindow", "Gender"))
        item = self.StudentInfo_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Account ID"))
        item = self.StudentInfo_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.StudentInfo_Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Gender"))
        item = self.StudentInfo_Table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Birthday"))
        item = self.StudentInfo_Table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Email"))
        item = self.StudentInfo_Table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Phone Number"))
        item = self.StudentInfo_Table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Address"))
        item = self.StudentInfo_Table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "AttendanceType"))
        item = self.StudentInfo_Table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Time"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
