# Form implementation generated from reading ui file 'Main_T.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 800)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:black;")
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 1604, 801))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.icon_only_widget = QtWidgets.QWidget(parent=self.layoutWidget)
        self.icon_only_widget.setMinimumSize(QtCore.QSize(71, 0))
        self.icon_only_widget.setMaximumSize(QtCore.QSize(71, 16777215))
        self.icon_only_widget.setStyleSheet("QWidget{\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:checked{\n"
"    background-color:white;\n"
"    border-radius:3px;\n"
"}")
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.icon_only_widget)
        self.verticalLayout_8.setContentsMargins(0, 30, 0, 0)
        self.verticalLayout_8.setSpacing(20)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(parent=self.icon_only_widget)
        self.label_3.setMaximumSize(QtCore.QSize(40, 40))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/image/logo_school.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(20)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Student_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.Student_1.setStyleSheet("")
        self.Student_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/book-open-reader (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap(":/image/book-open-reader.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.Student_1.setIcon(icon)
        self.Student_1.setIconSize(QtCore.QSize(25, 25))
        self.Student_1.setCheckable(True)
        self.Student_1.setAutoExclusive(True)
        self.Student_1.setObjectName("Student_1")
        self.verticalLayout_6.addWidget(self.Student_1)
        self.Account_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.Account_1.setStyleSheet("")
        self.Account_1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/workshop.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon1.addPixmap(QtGui.QPixmap(":/image/workshop (2).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.Account_1.setIcon(icon1)
        self.Account_1.setIconSize(QtCore.QSize(25, 25))
        self.Account_1.setCheckable(True)
        self.Account_1.setAutoExclusive(True)
        self.Account_1.setObjectName("Account_1")
        self.verticalLayout_6.addWidget(self.Account_1)
        self.FaceReg_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.FaceReg_1.setStyleSheet("")
        self.FaceReg_1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/image/face-viewfinder.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon2.addPixmap(QtGui.QPixmap(":/image/face-viewfinder (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.FaceReg_1.setIcon(icon2)
        self.FaceReg_1.setIconSize(QtCore.QSize(25, 25))
        self.FaceReg_1.setCheckable(True)
        self.FaceReg_1.setAutoExclusive(True)
        self.FaceReg_1.setObjectName("FaceReg_1")
        self.verticalLayout_6.addWidget(self.FaceReg_1)
        self.EnExHistory_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.EnExHistory_1.setStyleSheet("")
        self.EnExHistory_1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/image/calendar-clock-w.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon3.addPixmap(QtGui.QPixmap(":/image/calendar-clock.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.EnExHistory_1.setIcon(icon3)
        self.EnExHistory_1.setIconSize(QtCore.QSize(25, 25))
        self.EnExHistory_1.setCheckable(True)
        self.EnExHistory_1.setAutoExclusive(True)
        self.EnExHistory_1.setObjectName("EnExHistory_1")
        self.verticalLayout_6.addWidget(self.EnExHistory_1)
        self.Statistics_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.Statistics_1.setStyleSheet("")
        self.Statistics_1.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/image/chart-histogram (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon4.addPixmap(QtGui.QPixmap(":/image/chart-histogram.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.Statistics_1.setIcon(icon4)
        self.Statistics_1.setIconSize(QtCore.QSize(25, 25))
        self.Statistics_1.setCheckable(True)
        self.Statistics_1.setAutoExclusive(True)
        self.Statistics_1.setObjectName("Statistics_1")
        self.verticalLayout_6.addWidget(self.Statistics_1)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        spacerItem2 = QtWidgets.QSpacerItem(20, 287, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_8.addItem(spacerItem2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(15)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Settings_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.Settings_1.setStyleSheet("")
        self.Settings_1.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/image/settings (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon5.addPixmap(QtGui.QPixmap(":/image/settings.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.Settings_1.setIcon(icon5)
        self.Settings_1.setIconSize(QtCore.QSize(25, 25))
        self.Settings_1.setCheckable(True)
        self.Settings_1.setAutoExclusive(True)
        self.Settings_1.setObjectName("Settings_1")
        self.verticalLayout_5.addWidget(self.Settings_1)
        self.SignOut_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.SignOut_1.setStyleSheet("QPushButton{\n"
"    padding-left:2px;\n"
"}\n"
"")
        self.SignOut_1.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/image/sign-out-alt (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon6.addPixmap(QtGui.QPixmap(":/image/sign-out-alt.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.SignOut_1.setIcon(icon6)
        self.SignOut_1.setIconSize(QtCore.QSize(25, 25))
        self.SignOut_1.setCheckable(True)
        self.SignOut_1.setAutoExclusive(True)
        self.SignOut_1.setObjectName("SignOut_1")
        self.verticalLayout_5.addWidget(self.SignOut_1)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.gridLayout.addWidget(self.icon_only_widget, 0, 0, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.header_widget = QtWidgets.QWidget(parent=self.layoutWidget)
        self.header_widget.setObjectName("header_widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.header_widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = QtWidgets.QPushButton(parent=self.header_widget)
        self.pushButton.setStyleSheet("border:none")
        self.pushButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/image/menu.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon7)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        spacerItem3 = QtWidgets.QSpacerItem(700, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, 15, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.SearchHeader_Button = QtWidgets.QPushButton(parent=self.header_widget)
        self.SearchHeader_Button.setStyleSheet("border:none")
        self.SearchHeader_Button.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/image/search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.SearchHeader_Button.setIcon(icon8)
        self.SearchHeader_Button.setIconSize(QtCore.QSize(20, 20))
        self.SearchHeader_Button.setCheckable(True)
        self.SearchHeader_Button.setObjectName("SearchHeader_Button")
        self.horizontalLayout_3.addWidget(self.SearchHeader_Button)
        self.SearchHeader = QtWidgets.QLineEdit(parent=self.header_widget)
        self.SearchHeader.setMinimumSize(QtCore.QSize(0, 31))
        self.SearchHeader.setStyleSheet("QLineEdit{\n"
"    padding-left:20px;\n"
"    border:1px solid gray;\n"
"    border-radius:10px;\n"
"}")
        self.SearchHeader.setObjectName("SearchHeader")
        self.horizontalLayout_3.addWidget(self.SearchHeader)
        self.label_6 = QtWidgets.QLabel(parent=self.header_widget)
        self.label_6.setMaximumSize(QtCore.QSize(50, 50))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/image/profile_pic.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_9.addWidget(self.header_widget)
        self.main_widget = QtWidgets.QWidget(parent=self.layoutWidget)
        self.main_widget.setMinimumSize(QtCore.QSize(1260, 701))
        self.main_widget.setMaximumSize(QtCore.QSize(1300, 701))
        self.main_widget.setStyleSheet("")
        self.main_widget.setObjectName("main_widget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.main_widget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 1350, 800))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.StudentInfo_Header = QtWidgets.QLabel(parent=self.page)
        self.StudentInfo_Header.setGeometry(QtCore.QRect(10, 10, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        self.StudentInfo_Header.setFont(font)
        self.StudentInfo_Header.setObjectName("StudentInfo_Header")
        self.Add_Student_Button = QtWidgets.QPushButton(parent=self.page)
        self.Add_Student_Button.setGeometry(QtCore.QRect(10, 70, 111, 41))
        self.Add_Student_Button.setMinimumSize(QtCore.QSize(111, 41))
        self.Add_Student_Button.setMaximumSize(QtCore.QSize(111, 41))
        self.Add_Student_Button.setStyleSheet("QPushButton{    \n"
"    background-color: black;\n"
"    border:none;\n"
"    color:white;\n"
"    border-radius:8px;\n"
"    font-weight:bold;\n"
"    font-size:15px;\n"
"}")
        self.Add_Student_Button.setObjectName("Add_Student_Button")
        self.StudentInfo_Table = QtWidgets.QTableWidget(parent=self.page)
        self.StudentInfo_Table.setGeometry(QtCore.QRect(10, 180, 1281, 491))
        self.StudentInfo_Table.setMinimumSize(QtCore.QSize(0, 0))
        self.StudentInfo_Table.setStyleSheet("QHeaderView::section{\n"
"    font-weight:bold;\n"
"    background-color:black;\n"
"    color:white;\n"
"}\n"
"QTableWidget{    \n"
"    alternate-background-color: #B0BDFB;\n"
"    background-color:#F4F9FA;\n"
"}")
        self.StudentInfo_Table.setAlternatingRowColors(True)
        self.StudentInfo_Table.setObjectName("StudentInfo_Table")
        self.StudentInfo_Table.setColumnCount(8)
        self.StudentInfo_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.StudentInfo_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentInfo_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentInfo_Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentInfo_Table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentInfo_Table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentInfo_Table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentInfo_Table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentInfo_Table.setHorizontalHeaderItem(7, item)
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.page)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 130, 451, 42))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.GenderFind_Student_comboBox = QtWidgets.QComboBox(parent=self.layoutWidget1)
        self.GenderFind_Student_comboBox.setMinimumSize(QtCore.QSize(180, 40))
        self.GenderFind_Student_comboBox.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.GenderFind_Student_comboBox.setFont(font)
        self.GenderFind_Student_comboBox.setStyleSheet("QComboBox{\n"
"    border:2px solid white;\n"
"    border-radius:8px;\n"
"    padding:1px 15px 1px 3px;\n"
"    background-color: black;\n"
"    color:white;\n"
"    height:25px;\n"
"    padding-left:15px;\n"
"    font-weight:bold;\n"
"    selection-background-color:#298089;\n"
"}")
        self.GenderFind_Student_comboBox.setObjectName("GenderFind_Student_comboBox")
        self.GenderFind_Student_comboBox.addItem("")
        self.GenderFind_Student_comboBox.addItem("")
        self.GenderFind_Student_comboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.GenderFind_Student_comboBox)
        self.Search_Student = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.Search_Student.setMinimumSize(QtCore.QSize(0, 40))
        self.Search_Student.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Search_Student.setStyleSheet("QLineEdit{\n"
"    padding-left:20px;\n"
"    border:1px solid gray;\n"
"    border-radius:10px;\n"
"}")
        self.Search_Student.setObjectName("Search_Student")
        self.horizontalLayout_5.addWidget(self.Search_Student)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.AccountInfo_Table = QtWidgets.QTableWidget(parent=self.page_2)
        self.AccountInfo_Table.setGeometry(QtCore.QRect(10, 180, 1250, 491))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AccountInfo_Table.setFont(font)
        self.AccountInfo_Table.setStyleSheet("QHeaderView::section{\n"
"    font-weight:bold;\n"
"    background-color:black;\n"
"    color:white;\n"
"}\n"
"QTableWidget{    \n"
"    alternate-background-color: #B0BDFB;\n"
"    background-color:#F4F9FA;\n"
"}")
        self.AccountInfo_Table.setAlternatingRowColors(True)
        self.AccountInfo_Table.setObjectName("AccountInfo_Table")
        self.AccountInfo_Table.setColumnCount(10)
        self.AccountInfo_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.AccountInfo_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.AccountInfo_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.AccountInfo_Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.AccountInfo_Table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.AccountInfo_Table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.AccountInfo_Table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.AccountInfo_Table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.AccountInfo_Table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.AccountInfo_Table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.AccountInfo_Table.setHorizontalHeaderItem(9, item)
        self.layoutWidget_3 = QtWidgets.QWidget(parent=self.page_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 130, 621, 42))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.GenderFind_Account_comboBox = QtWidgets.QComboBox(parent=self.layoutWidget_3)
        self.GenderFind_Account_comboBox.setMinimumSize(QtCore.QSize(180, 40))
        self.GenderFind_Account_comboBox.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.GenderFind_Account_comboBox.setFont(font)
        self.GenderFind_Account_comboBox.setStyleSheet("QComboBox{\n"
"    border:2px solid white;\n"
"    border-radius:8px;\n"
"    padding:1px 15px 1px 3px;\n"
"    background-color: black;\n"
"    color:white;\n"
"    height:25px;\n"
"    padding-left:15px;\n"
"    font-weight:bold;\n"
"    selection-background-color:#298089;\n"
"}")
        self.GenderFind_Account_comboBox.setObjectName("GenderFind_Account_comboBox")
        self.GenderFind_Account_comboBox.addItem("")
        self.GenderFind_Account_comboBox.addItem("")
        self.GenderFind_Account_comboBox.addItem("")
        self.horizontalLayout_19.addWidget(self.GenderFind_Account_comboBox)
        self.RolesFind_Account_comboBox = QtWidgets.QComboBox(parent=self.layoutWidget_3)
        self.RolesFind_Account_comboBox.setMinimumSize(QtCore.QSize(180, 40))
        self.RolesFind_Account_comboBox.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.RolesFind_Account_comboBox.setFont(font)
        self.RolesFind_Account_comboBox.setStyleSheet("QComboBox{\n"
"    border:2px solid white;\n"
"    border-radius:8px;\n"
"    padding:1px 15px 1px 3px;\n"
"    background-color: black;\n"
"    color:white;\n"
"    height:25px;\n"
"    padding-left:15px;\n"
"    font-weight:bold;\n"
"    selection-background-color:#298089;\n"
"}")
        self.RolesFind_Account_comboBox.setObjectName("RolesFind_Account_comboBox")
        self.RolesFind_Account_comboBox.addItem("")
        self.RolesFind_Account_comboBox.addItem("")
        self.RolesFind_Account_comboBox.addItem("")
        self.horizontalLayout_19.addWidget(self.RolesFind_Account_comboBox)
        self.Search_Account_LineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget_3)
        self.Search_Account_LineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.Search_Account_LineEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Search_Account_LineEdit.setStyleSheet("QLineEdit{\n"
"    padding-left:20px;\n"
"    border:1px solid gray;\n"
"    border-radius:10px;\n"
"}")
        self.Search_Account_LineEdit.setObjectName("Search_Account_LineEdit")
        self.horizontalLayout_19.addWidget(self.Search_Account_LineEdit)
        self.AccountInfo_Header = QtWidgets.QLabel(parent=self.page_2)
        self.AccountInfo_Header.setGeometry(QtCore.QRect(10, 10, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        self.AccountInfo_Header.setFont(font)
        self.AccountInfo_Header.setObjectName("AccountInfo_Header")
        self.Add_Account_Button = QtWidgets.QPushButton(parent=self.page_2)
        self.Add_Account_Button.setGeometry(QtCore.QRect(10, 70, 111, 41))
        self.Add_Account_Button.setMinimumSize(QtCore.QSize(111, 41))
        self.Add_Account_Button.setMaximumSize(QtCore.QSize(111, 41))
        self.Add_Account_Button.setStyleSheet("QPushButton{    \n"
"    background-color: black;\n"
"    border:none;\n"
"    color:white;\n"
"    border-radius:8px;\n"
"    font-weight:bold;\n"
"    font-size:15px;\n"
"}")
        self.Add_Account_Button.setObjectName("Add_Account_Button")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.Table_history = QtWidgets.QTableWidget(parent=self.page_3)
        self.Table_history.setGeometry(QtCore.QRect(40, 40, 1201, 491))
        self.Table_history.setMinimumSize(QtCore.QSize(1201, 491))
        self.Table_history.setMaximumSize(QtCore.QSize(1201, 491))
        self.Table_history.setStyleSheet("QHeaderView::section{\n"
"    font-weight:bold;\n"
"    background-color:black;\n"
"    color:white;\n"
"}\n"
"QTableWidget{    \n"
"    alternate-background-color: #B0BDFB;\n"
"    background-color:#F4F9FA;\n"
"}")
        self.Table_history.setAlternatingRowColors(True)
        self.Table_history.setObjectName("Table_history")
        self.Table_history.setColumnCount(4)
        self.Table_history.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Table_history.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_history.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_history.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_history.setHorizontalHeaderItem(3, item)
        self.hienthi_history = QtWidgets.QPushButton(parent=self.page_3)
        self.hienthi_history.setGeometry(QtCore.QRect(580, 540, 101, 32))
        self.hienthi_history.setMinimumSize(QtCore.QSize(100, 30))
        self.hienthi_history.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.hienthi_history.setObjectName("hienthi_history")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setStyleSheet("QLineEdit{\n"
"    border: 1px solid gray;\n"
"    border-radius:6px;\n"
"    padding-left:15px;\n"
"    height:30px;\n"
"}\n"
"QDateEdit{\n"
"    border:1px solid gray;\n"
"    border-radius:6px;\n"
"    padding-left:15px;\n"
"    height:28px;\n"
"}\n"
"QDateTimeEdit{\n"
"    border:1px solid gray;\n"
"    border-radius:6px;\n"
"    padding-left:15px;\n"
"    height:28px;\n"
"}\n"
"QComboBox{\n"
"    border:2px solid white;\n"
"    border-radius:8px;\n"
"    padding:1px 15px 1px 3px;\n"
"    background-color: black;\n"
"    color:white;\n"
"    height:25px;\n"
"    padding-left:15px;\n"
"    font-weight:bold;\n"
"    selection-background-color:#298089;\n"
"}\n"
"")
        self.page_4.setObjectName("page_4")
        self.layoutWidget_2 = QtWidgets.QWidget(parent=self.page_4)
        self.layoutWidget_2.setGeometry(QtCore.QRect(40, 240, 481, 457))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_8 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_12.addWidget(self.label_8)
        self.ID_FaceReg_Student_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget_2)
        self.ID_FaceReg_Student_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.ID_FaceReg_Student_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ID_FaceReg_Student_lineEdit.setFont(font)
        self.ID_FaceReg_Student_lineEdit.setObjectName("ID_FaceReg_Student_lineEdit")
        self.verticalLayout_12.addWidget(self.ID_FaceReg_Student_lineEdit)
        self.verticalLayout_10.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_9 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_13.addWidget(self.label_9)
        self.Name_FaceReg_Student_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget_2)
        self.Name_FaceReg_Student_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.Name_FaceReg_Student_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Name_FaceReg_Student_lineEdit.setFont(font)
        self.Name_FaceReg_Student_lineEdit.setObjectName("Name_FaceReg_Student_lineEdit")
        self.verticalLayout_13.addWidget(self.Name_FaceReg_Student_lineEdit)
        self.verticalLayout_10.addLayout(self.verticalLayout_13)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_13 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_14.addWidget(self.label_13)
        self.Gender_FaceReg_Student_comboBox = QtWidgets.QComboBox(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.Gender_FaceReg_Student_comboBox.setFont(font)
        self.Gender_FaceReg_Student_comboBox.setObjectName("Gender_FaceReg_Student_comboBox")
        self.Gender_FaceReg_Student_comboBox.addItem("")
        self.Gender_FaceReg_Student_comboBox.addItem("")
        self.verticalLayout_14.addWidget(self.Gender_FaceReg_Student_comboBox)
        self.horizontalLayout_6.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_14 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_15.addWidget(self.label_14)
        self.Birth_FaceReg_Student_dateEdit = QtWidgets.QDateEdit(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Birth_FaceReg_Student_dateEdit.setFont(font)
        self.Birth_FaceReg_Student_dateEdit.setObjectName("Birth_FaceReg_Student_dateEdit")
        self.verticalLayout_15.addWidget(self.Birth_FaceReg_Student_dateEdit)
        self.horizontalLayout_6.addLayout(self.verticalLayout_15)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_15 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_16.addWidget(self.label_15)
        self.Phone_FaceReg_Student_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget_2)
        self.Phone_FaceReg_Student_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.Phone_FaceReg_Student_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Phone_FaceReg_Student_lineEdit.setFont(font)
        self.Phone_FaceReg_Student_lineEdit.setObjectName("Phone_FaceReg_Student_lineEdit")
        self.verticalLayout_16.addWidget(self.Phone_FaceReg_Student_lineEdit)
        self.verticalLayout_10.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_16 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_17.addWidget(self.label_16)
        self.Email_FaceReg_Student_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget_2)
        self.Email_FaceReg_Student_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.Email_FaceReg_Student_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Email_FaceReg_Student_lineEdit.setFont(font)
        self.Email_FaceReg_Student_lineEdit.setObjectName("Email_FaceReg_Student_lineEdit")
        self.verticalLayout_17.addWidget(self.Email_FaceReg_Student_lineEdit)
        self.verticalLayout_10.addLayout(self.verticalLayout_17)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_17 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_18.addWidget(self.label_17)
        self.Address_FaceReg_Student_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget_2)
        self.Address_FaceReg_Student_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.Address_FaceReg_Student_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Address_FaceReg_Student_lineEdit.setFont(font)
        self.Address_FaceReg_Student_lineEdit.setObjectName("Address_FaceReg_Student_lineEdit")
        self.verticalLayout_18.addWidget(self.Address_FaceReg_Student_lineEdit)
        self.verticalLayout_10.addLayout(self.verticalLayout_18)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.attendance_status_label = QtWidgets.QLabel(parent=self.layoutWidget_2)
        self.attendance_status_label.setMinimumSize(QtCore.QSize(0, 30))
        self.attendance_status_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.attendance_status_label.setText("")
        self.attendance_status_label.setObjectName("attendance_status_label")
        self.horizontalLayout_8.addWidget(self.attendance_status_label)
        self.time_label = QtWidgets.QLabel(parent=self.layoutWidget_2)
        self.time_label.setMinimumSize(QtCore.QSize(0, 30))
        self.time_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.time_label.setText("")
        self.time_label.setObjectName("time_label")
        self.horizontalLayout_8.addWidget(self.time_label)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.FaceReg_CameraInfo_label = QtWidgets.QLabel(parent=self.page_4)
        self.FaceReg_CameraInfo_label.setGeometry(QtCore.QRect(670, 640, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.FaceReg_CameraInfo_label.setFont(font)
        self.FaceReg_CameraInfo_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.FaceReg_CameraInfo_label.setText("")
        self.FaceReg_CameraInfo_label.setObjectName("FaceReg_CameraInfo_label")
        self.layoutWidget2 = QtWidgets.QWidget(parent=self.page_4)
        self.layoutWidget2.setGeometry(QtCore.QRect(740, 560, 301, 51))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(30)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.OpenCamera = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.OpenCamera.setMinimumSize(QtCore.QSize(130, 0))
        self.OpenCamera.setMaximumSize(QtCore.QSize(130, 16777215))
        self.OpenCamera.setStyleSheet("QPushButton{\n"
"    border:2px solid white;\n"
"    border-radius:8px;\n"
"    background-color: black;\n"
"    color:white;\n"
"    height:40px;\n"
"    font-weight:bold;\n"
"    selection-background-color:#298089;\n"
"}")
        self.OpenCamera.setObjectName("OpenCamera")
        self.horizontalLayout_7.addWidget(self.OpenCamera)
        self.CloseCamera = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.CloseCamera.setMinimumSize(QtCore.QSize(130, 0))
        self.CloseCamera.setMaximumSize(QtCore.QSize(130, 16777215))
        self.CloseCamera.setStyleSheet("QPushButton{\n"
"    border:2px solid gray;\n"
"    border-radius:8px;\n"
"    background-color: white;\n"
"    color: black;\n"
"    height:40px;\n"
"    font-weight:bold;\n"
"    selection-background-color:#298089;\n"
"}")
        self.CloseCamera.setObjectName("CloseCamera")
        self.horizontalLayout_7.addWidget(self.CloseCamera)
        self.FaceReg_Camera_label = QtWidgets.QLabel(parent=self.page_4)
        self.FaceReg_Camera_label.setGeometry(QtCore.QRect(620, 0, 551, 551))
        self.FaceReg_Camera_label.setMinimumSize(QtCore.QSize(551, 551))
        self.FaceReg_Camera_label.setMaximumSize(QtCore.QSize(601, 601))
        self.FaceReg_Camera_label.setStyleSheet("\n"
"background-color: rgb(200, 200, 200);")
        self.FaceReg_Camera_label.setText("")
        self.FaceReg_Camera_label.setObjectName("FaceReg_Camera_label")
        self.FaceReg_CameraStudent_label = QtWidgets.QLabel(parent=self.page_4)
        self.FaceReg_CameraStudent_label.setGeometry(QtCore.QRect(150, 0, 221, 221))
        self.FaceReg_CameraStudent_label.setMinimumSize(QtCore.QSize(221, 221))
        self.FaceReg_CameraStudent_label.setMaximumSize(QtCore.QSize(221, 221))
        self.FaceReg_CameraStudent_label.setStyleSheet("background-color: rgb(200, 200, 200);\n"
"padding-left:20px;")
        self.FaceReg_CameraStudent_label.setText("")
        self.FaceReg_CameraStudent_label.setObjectName("FaceReg_CameraStudent_label")
        self.attendance_type_combo = QtWidgets.QComboBox(parent=self.page_4)
        self.attendance_type_combo.setGeometry(QtCore.QRect(0, 0, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.attendance_type_combo.setFont(font)
        self.attendance_type_combo.setObjectName("attendance_type_combo")
        self.attendance_type_combo.addItem("")
        self.attendance_type_combo.addItem("")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setStyleSheet("\n"
"    QGroupBox {\n"
"      border: 2px solid #bdc3c7;\n"
"      border-radius: 5px;\n"
"      margin-top: 10px;\n"
"      padding: 15px;\n"
"    }\n"
"    QGroupBox::title {\n"
"      padding: 0 10px;\n"
"      background-color: #ffffff;\n"
"    }\n"
"    QLineEdit, QDateEdit {\n"
"      padding: 8px;\n"
"      border: 1px solid #bdc3c7;\n"
"      border-radius: 4px;\n"
"      background-color: #ffffff;\n"
"    }\n"
"    QLineEdit:focus, QDateEdit:focus {\n"
"      border: 2px solid #3498db;\n"
"    }\n"
"    QPushButton {\n"
"      background-color: #3498db;\n"
"      color: white;\n"
"      border: none;\n"
"      border-radius: 4px;\n"
"      padding: 8px 16px;\n"
"      font-weight: bold;\n"
"    }\n"
"    QPushButton:hover {\n"
"      background-color: #2980b9;\n"
"    }\n"
"    QPushButton:pressed {\n"
"      background-color: #2472a4;\n"
"    }\n"
"    QTableWidget {\n"
"      border: 1px solid #bdc3c7;\n"
"      border-radius: 4px;\n"
"      gridline-color: #ecf0f1;\n"
"      selection-background-color: #3498db;\n"
"      selection-color: #ffffff;\n"
"    }\n"
"    QTableWidget::item {\n"
"      padding: 5px;\n"
"    }\n"
"    QHeaderView::section {\n"
"      background-color: #f8f9fa;\n"
"      padding: 5px;\n"
"      border: none;\n"
"      font-weight: bold;\n"
"    }\n"
"    QLabel {\n"
"      color: #2c3e50;\n"
"    }\n"
"   ")
        self.page_5.setObjectName("page_5")
        self.layoutWidget3 = QtWidgets.QWidget(parent=self.page_5)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 10, 1203, 652))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.groupBox_dau = QtWidgets.QGroupBox(parent=self.layoutWidget3)
        self.groupBox_dau.setMinimumSize(QtCore.QSize(660, 150))
        self.groupBox_dau.setMaximumSize(QtCore.QSize(660, 150))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setKerning(True)
        self.groupBox_dau.setFont(font)
        self.groupBox_dau.setObjectName("groupBox_dau")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_dau)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.nhapmsv_2 = QtWidgets.QLineEdit(parent=self.groupBox_dau)
        self.nhapmsv_2.setMinimumSize(QtCore.QSize(180, 30))
        self.nhapmsv_2.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sitka Small Semibold")
        font.setPointSize(9)
        font.setBold(True)
        self.nhapmsv_2.setFont(font)
        self.nhapmsv_2.setObjectName("nhapmsv_2")
        self.gridLayout_3.addWidget(self.nhapmsv_2, 2, 1, 1, 1)
        self.EnExHistoryFindbatdau_DateEdit = QtWidgets.QDateEdit(parent=self.groupBox_dau)
        self.EnExHistoryFindbatdau_DateEdit.setMinimumSize(QtCore.QSize(180, 30))
        self.EnExHistoryFindbatdau_DateEdit.setMaximumSize(QtCore.QSize(180, 16777215))
        self.EnExHistoryFindbatdau_DateEdit.setObjectName("EnExHistoryFindbatdau_DateEdit")
        self.gridLayout_3.addWidget(self.EnExHistoryFindbatdau_DateEdit, 0, 1, 1, 1)
        self.label_EnExHistoryEnd = QtWidgets.QLabel(parent=self.groupBox_dau)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_EnExHistoryEnd.setFont(font)
        self.label_EnExHistoryEnd.setObjectName("label_EnExHistoryEnd")
        self.gridLayout_3.addWidget(self.label_EnExHistoryEnd, 0, 3, 1, 1)
        self.label_nhapmsv_6 = QtWidgets.QLabel(parent=self.groupBox_dau)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_nhapmsv_6.setFont(font)
        self.label_nhapmsv_6.setObjectName("label_nhapmsv_6")
        self.gridLayout_3.addWidget(self.label_nhapmsv_6, 2, 0, 1, 1)
        self.label_EnExHistoryStart = QtWidgets.QLabel(parent=self.groupBox_dau)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_EnExHistoryStart.setFont(font)
        self.label_EnExHistoryStart.setObjectName("label_EnExHistoryStart")
        self.gridLayout_3.addWidget(self.label_EnExHistoryStart, 0, 0, 1, 1)
        self.EnExHistoryFindketthuc_DateEdit = QtWidgets.QDateEdit(parent=self.groupBox_dau)
        self.EnExHistoryFindketthuc_DateEdit.setMinimumSize(QtCore.QSize(180, 30))
        self.EnExHistoryFindketthuc_DateEdit.setObjectName("EnExHistoryFindketthuc_DateEdit")
        self.gridLayout_3.addWidget(self.EnExHistoryFindketthuc_DateEdit, 0, 4, 1, 1)
        self.Find_EnExHistory_Button = QtWidgets.QPushButton(parent=self.groupBox_dau)
        self.Find_EnExHistory_Button.setMinimumSize(QtCore.QSize(100, 30))
        self.Find_EnExHistory_Button.setObjectName("Find_EnExHistory_Button")
        self.gridLayout_3.addWidget(self.Find_EnExHistory_Button, 2, 3, 1, 1)
        self.Export_PDF_Button = QtWidgets.QPushButton(parent=self.groupBox_dau)
        self.Export_PDF_Button.setMinimumSize(QtCore.QSize(150, 41))
        self.Export_PDF_Button.setMaximumSize(QtCore.QSize(150, 41))
        self.Export_PDF_Button.setStyleSheet("QPushButton{        \n"
"    background-color: rgb(255, 60, 1);\n"
"    border:none;\n"
"    color:white;\n"
"    border-radius:8px;\n"
"    font-weight:bold;\n"
"    font-size:15px;\n"
"}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/image/pdf.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Export_PDF_Button.setIcon(icon9)
        self.Export_PDF_Button.setObjectName("Export_PDF_Button")
        self.gridLayout_3.addWidget(self.Export_PDF_Button, 2, 4, 1, 1)
        self.horizontalLayout_9.addWidget(self.groupBox_dau)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.verticalLayout_11.addLayout(self.horizontalLayout_9)
        self.EnExHistory_Table = QtWidgets.QTableWidget(parent=self.layoutWidget3)
        self.EnExHistory_Table.setMinimumSize(QtCore.QSize(1201, 491))
        self.EnExHistory_Table.setMaximumSize(QtCore.QSize(1201, 491))
        self.EnExHistory_Table.setStyleSheet("QHeaderView::section{\n"
"    font-weight:bold;\n"
"    background-color:black;\n"
"    color:white;\n"
"}\n"
"QTableWidget{    \n"
"    alternate-background-color: #B0BDFB;\n"
"    background-color:#F4F9FA;\n"
"}")
        self.EnExHistory_Table.setAlternatingRowColors(True)
        self.EnExHistory_Table.setObjectName("EnExHistory_Table")
        self.EnExHistory_Table.setColumnCount(6)
        self.EnExHistory_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.EnExHistory_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.EnExHistory_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.EnExHistory_Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.EnExHistory_Table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.EnExHistory_Table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.EnExHistory_Table.setHorizontalHeaderItem(5, item)
        self.verticalLayout_11.addWidget(self.EnExHistory_Table)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setStyleSheet("QLineEdit{\n"
"    border: 1px solid gray;\n"
"    border-radius:6px;\n"
"    padding-left:15px;\n"
"    height:30px;\n"
"}\n"
"QPushButton{\n"
"    border: 1px solid gray;\n"
"    border-radius:6px;\n"
"    padding-left:15px;\n"
"    height:30px;\n"
"}\n"
"QDateEdit{\n"
"    border:1px solid gray;\n"
"    border-radius:6px;\n"
"    padding-left:15px;\n"
"    height:28px;\n"
"}\n"
"QDateTimeEdit{\n"
"    border:1px solid gray;\n"
"    border-radius:6px;\n"
"    padding-left:15px;\n"
"    height:28px;\n"
"}\n"
"QComboBox{\n"
"    border:2px solid white;\n"
"    border-radius:8px;\n"
"    padding:1px 15px 1px 3px;\n"
"    background-color: black;\n"
"    color:white;\n"
"    height:25px;\n"
"    padding-left:15px;\n"
"    font-weight:bold;\n"
"    selection-background-color:#298089;\n"
"}\n"
"")
        self.page_6.setObjectName("page_6")
        self.label_fromdayp7 = QtWidgets.QLabel(parent=self.page_6)
        self.label_fromdayp7.setGeometry(QtCore.QRect(80, 20, 61, 21))
        self.label_fromdayp7.setObjectName("label_fromdayp7")
        self.bt_taothongke = QtWidgets.QPushButton(parent=self.page_6)
        self.bt_taothongke.setGeometry(QtCore.QRect(850, 10, 171, 28))
        self.bt_taothongke.setObjectName("bt_taothongke")
        self.comboBoxpage_7 = QtWidgets.QComboBox(parent=self.page_6)
        self.comboBoxpage_7.setGeometry(QtCore.QRect(510, 10, 311, 31))
        self.comboBoxpage_7.setObjectName("comboBoxpage_7")
        self.comboBoxpage_7.addItem("")
        self.comboBoxpage_7.addItem("")
        self.comboBoxpage_7.addItem("")
        self.comboBoxpage_7.addItem("")
        self.comboBoxpage_7.addItem("")
        self.comboBoxpage_7.addItem("")
        self.dateEditpage_7 = QtWidgets.QDateEdit(parent=self.page_6)
        self.dateEditpage_7.setGeometry(QtCore.QRect(140, 20, 110, 22))
        self.dateEditpage_7.setObjectName("dateEditpage_7")
        self.bt_hienthibd = QtWidgets.QPushButton(parent=self.page_6)
        self.bt_hienthibd.setGeometry(QtCore.QRect(1060, 10, 191, 28))
        self.bt_hienthibd.setObjectName("bt_hienthibd")
        self.dateEdit_2page_7 = QtWidgets.QDateEdit(parent=self.page_6)
        self.dateEdit_2page_7.setGeometry(QtCore.QRect(360, 20, 110, 22))
        self.dateEdit_2page_7.setObjectName("dateEdit_2page_7")
        self.label_todayp7 = QtWidgets.QLabel(parent=self.page_6)
        self.label_todayp7.setGeometry(QtCore.QRect(290, 20, 55, 16))
        self.label_todayp7.setObjectName("label_todayp7")
        self.vunghienthibieudo_page7 = QtWidgets.QWidget(parent=self.page_6)
        self.vunghienthibieudo_page7.setGeometry(QtCore.QRect(190, 60, 991, 611))
        self.vunghienthibieudo_page7.setObjectName("vunghienthibieudo_page7")
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.widget = QtWidgets.QWidget(parent=self.page_7)
        self.widget.setGeometry(QtCore.QRect(170, 80, 661, 501))
        self.widget.setObjectName("widget")
        self.label_12 = QtWidgets.QLabel(parent=self.widget)
        self.label_12.setGeometry(QtCore.QRect(320, 240, 161, 131))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.stackedWidget.addWidget(self.page_7)
        self.verticalLayout_9.addWidget(self.main_widget)
        self.gridLayout.addLayout(self.verticalLayout_9, 0, 2, 1, 1)
        self.icon_text_widget = QtWidgets.QWidget(parent=self.layoutWidget)
        self.icon_text_widget.setStyleSheet("QWidget{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color:white\n"
"\n"
"}\n"
"QPushButton{\n"
"    color: white;\n"
"    \n"
"    padding-left:20px;\n"
"    border:none;\n"
"    height:30px;\n"
"}\n"
"")
        self.icon_text_widget.setObjectName("icon_text_widget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.icon_text_widget)
        self.verticalLayout_7.setContentsMargins(15, 30, 15, 0)
        self.verticalLayout_7.setSpacing(20)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(2, -1, -1, -1)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.icon_text_widget)
        self.label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.label_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/image/logo_school.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(parent=self.icon_text_widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 0, 10, -1)
        self.verticalLayout_3.setSpacing(23)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Student_2 = QtWidgets.QPushButton(parent=self.icon_text_widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        font.setBold(False)
        self.Student_2.setFont(font)
        self.Student_2.setStyleSheet("QPushButton{\n"
"    padding-left:-20px;\n"
"}\n"
"QPushButton:checked{\n"
"    background-color:white;\n"
"    border-radius:3px;\n"
"    color: black;\n"
"    font-weight:bold;\n"
"}")
        self.Student_2.setIcon(icon)
        self.Student_2.setIconSize(QtCore.QSize(25, 25))
        self.Student_2.setCheckable(True)
        self.Student_2.setAutoExclusive(True)
        self.Student_2.setObjectName("Student_2")
        self.verticalLayout_3.addWidget(self.Student_2)
        self.ManageAcounts = QtWidgets.QFrame(parent=self.icon_text_widget)
        self.ManageAcounts.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ManageAcounts.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ManageAcounts.setObjectName("ManageAcounts")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.ManageAcounts)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Accounts_2 = QtWidgets.QPushButton(parent=self.ManageAcounts)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        self.Accounts_2.setFont(font)
        self.Accounts_2.setStyleSheet("QPushButton{\n"
"    padding-left:-20px;\n"
"}\n"
"QPushButton:checked{\n"
"    background-color:white;\n"
"    border-radius:3px;\n"
"    color: black;\n"
"    font-weight:bold;\n"
"}")
        self.Accounts_2.setIcon(icon1)
        self.Accounts_2.setIconSize(QtCore.QSize(25, 25))
        self.Accounts_2.setCheckable(True)
        self.Accounts_2.setAutoExclusive(True)
        self.Accounts_2.setObjectName("Accounts_2")
        self.verticalLayout.addWidget(self.Accounts_2)
        self.Account_dropdown = QtWidgets.QFrame(parent=self.ManageAcounts)
        self.Account_dropdown.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Account_dropdown.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Account_dropdown.setObjectName("Account_dropdown")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Account_dropdown)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Account = QtWidgets.QPushButton(parent=self.Account_dropdown)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        self.Account.setFont(font)
        self.Account.setStyleSheet("QPushButton{\n"
"    padding-left:-20px\n"
"}\n"
"QPushButton:checked{\n"
"    background-color:white;\n"
"    border-radius:3px;\n"
"    color: black;\n"
"    font-weight:bold;\n"
"}\n"
"")
        self.Account.setCheckable(True)
        self.Account.setObjectName("Account")
        self.verticalLayout_2.addWidget(self.Account)
        self.LogHistory = QtWidgets.QPushButton(parent=self.Account_dropdown)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        self.LogHistory.setFont(font)
        self.LogHistory.setStyleSheet("QPushButton:checked{\n"
"    background-color:white;\n"
"    border-radius:3px;\n"
"    color: black;\n"
"    font-weight:bold;\n"
"}")
        self.LogHistory.setCheckable(True)
        self.LogHistory.setObjectName("LogHistory")
        self.verticalLayout_2.addWidget(self.LogHistory)
        self.verticalLayout.addWidget(self.Account_dropdown)
        self.verticalLayout_3.addWidget(self.ManageAcounts)
        self.FaceReg_2 = QtWidgets.QPushButton(parent=self.icon_text_widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        self.FaceReg_2.setFont(font)
        self.FaceReg_2.setStyleSheet("QPushButton{\n"
"    padding-left:-20px;\n"
"}\n"
"QPushButton:checked{\n"
"    background-color:white;\n"
"    border-radius:3px;\n"
"    color: black;\n"
"    font-weight:bold;\n"
"}")
        self.FaceReg_2.setIcon(icon2)
        self.FaceReg_2.setIconSize(QtCore.QSize(25, 25))
        self.FaceReg_2.setCheckable(True)
        self.FaceReg_2.setAutoExclusive(True)
        self.FaceReg_2.setObjectName("FaceReg_2")
        self.verticalLayout_3.addWidget(self.FaceReg_2)
        self.EnExHistory_2 = QtWidgets.QPushButton(parent=self.icon_text_widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        self.EnExHistory_2.setFont(font)
        self.EnExHistory_2.setStyleSheet("QPushButton{\n"
"    padding-left:2px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color:white;\n"
"    border-radius:3px;\n"
"    color: black;\n"
"}")
        self.EnExHistory_2.setIcon(icon3)
        self.EnExHistory_2.setIconSize(QtCore.QSize(25, 25))
        self.EnExHistory_2.setCheckable(True)
        self.EnExHistory_2.setAutoExclusive(True)
        self.EnExHistory_2.setObjectName("EnExHistory_2")
        self.verticalLayout_3.addWidget(self.EnExHistory_2)
        self.Statistics_2 = QtWidgets.QPushButton(parent=self.icon_text_widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        self.Statistics_2.setFont(font)
        self.Statistics_2.setStyleSheet("QPushButton{\n"
"    padding-left:-75px;\n"
"}\n"
"QPushButton:checked{\n"
"    background-color:white;\n"
"    border-radius:3px;\n"
"    color: black;\n"
"    font-weight:bold;\n"
"}")
        self.Statistics_2.setIcon(icon4)
        self.Statistics_2.setIconSize(QtCore.QSize(25, 25))
        self.Statistics_2.setCheckable(True)
        self.Statistics_2.setAutoExclusive(True)
        self.Statistics_2.setObjectName("Statistics_2")
        self.verticalLayout_3.addWidget(self.Statistics_2)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 194, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_7.addItem(spacerItem6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Settings_2 = QtWidgets.QPushButton(parent=self.icon_text_widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        self.Settings_2.setFont(font)
        self.Settings_2.setStyleSheet("QPushButton{\n"
"    padding-left:-90px;\n"
"}\n"
"QPushButton:checked{\n"
"    background-color:white;\n"
"    border-radius:3px;\n"
"    color: black;\n"
"    font-weight:bold;\n"
"}")
        self.Settings_2.setIcon(icon5)
        self.Settings_2.setIconSize(QtCore.QSize(25, 25))
        self.Settings_2.setCheckable(True)
        self.Settings_2.setObjectName("Settings_2")
        self.verticalLayout_4.addWidget(self.Settings_2)
        self.SignOut_2 = QtWidgets.QPushButton(parent=self.icon_text_widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        self.SignOut_2.setFont(font)
        self.SignOut_2.setStyleSheet("QPushButton{\n"
"    padding-left:-85px;\n"
"}\n"
"QPushButton:checked{\n"
"    background-color:white;\n"
"    border-radius:3px;\n"
"    color: black;\n"
"    font-weight:bold;\n"
"}")
        self.SignOut_2.setIcon(icon6)
        self.SignOut_2.setIconSize(QtCore.QSize(25, 25))
        self.SignOut_2.setCheckable(True)
        self.SignOut_2.setObjectName("SignOut_2")
        self.verticalLayout_4.addWidget(self.SignOut_2)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.gridLayout.addWidget(self.icon_text_widget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Accounts_2.toggled['bool'].connect(self.Account_dropdown.setHidden) # type: ignore
        self.Student_1.toggled['bool'].connect(self.Student_2.setChecked) # type: ignore
        self.Account_1.toggled['bool'].connect(self.Accounts_2.setChecked) # type: ignore
        self.FaceReg_1.toggled['bool'].connect(self.FaceReg_2.setChecked) # type: ignore
        self.EnExHistory_1.toggled['bool'].connect(self.EnExHistory_2.setChecked) # type: ignore
        self.Statistics_1.toggled['bool'].connect(self.Statistics_2.setChecked) # type: ignore
        self.Settings_1.toggled['bool'].connect(self.Settings_2.setChecked) # type: ignore
        self.SignOut_1.toggled['bool'].connect(self.SignOut_2.setChecked) # type: ignore
        self.SignOut_1.toggled['bool'].connect(MainWindow.close) # type: ignore
        self.SignOut_2.toggled['bool'].connect(MainWindow.close) # type: ignore
        self.pushButton.toggled['bool'].connect(self.icon_text_widget.setHidden) # type: ignore
        self.pushButton.toggled['bool'].connect(self.icon_only_widget.setVisible) # type: ignore
        self.Student_2.toggled['bool'].connect(self.Account_dropdown.setHidden) # type: ignore
        self.FaceReg_2.toggled['bool'].connect(self.Account_dropdown.setHidden) # type: ignore
        self.EnExHistory_2.toggled['bool'].connect(self.Account_dropdown.setHidden) # type: ignore
        self.Statistics_2.toggled['bool'].connect(self.Account_dropdown.setHidden) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SearchHeader.setPlaceholderText(_translate("MainWindow", "Search Here..."))
        self.StudentInfo_Header.setText(_translate("MainWindow", "Student info"))
        self.Add_Student_Button.setText(_translate("MainWindow", "Add Student"))
        item = self.StudentInfo_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Student ID"))
        item = self.StudentInfo_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.StudentInfo_Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Gender"))
        item = self.StudentInfo_Table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Birthday"))
        item = self.StudentInfo_Table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Phone Number"))
        item = self.StudentInfo_Table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Email"))
        item = self.StudentInfo_Table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Address"))
        item = self.StudentInfo_Table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Actions"))
        self.GenderFind_Student_comboBox.setItemText(0, _translate("MainWindow", "GenderDefault"))
        self.GenderFind_Student_comboBox.setItemText(1, _translate("MainWindow", "Male"))
        self.GenderFind_Student_comboBox.setItemText(2, _translate("MainWindow", "Female"))
        self.Search_Student.setPlaceholderText(_translate("MainWindow", "Search Name/ID..."))
        item = self.AccountInfo_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Account ID"))
        item = self.AccountInfo_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.AccountInfo_Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Gender"))
        item = self.AccountInfo_Table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Username"))
        item = self.AccountInfo_Table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Role"))
        item = self.AccountInfo_Table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Birthday"))
        item = self.AccountInfo_Table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Email"))
        item = self.AccountInfo_Table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Phone Number"))
        item = self.AccountInfo_Table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Address"))
        item = self.AccountInfo_Table.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Actions"))
        self.GenderFind_Account_comboBox.setItemText(0, _translate("MainWindow", "GenderDefault"))
        self.GenderFind_Account_comboBox.setItemText(1, _translate("MainWindow", "Male"))
        self.GenderFind_Account_comboBox.setItemText(2, _translate("MainWindow", "Female"))
        self.RolesFind_Account_comboBox.setItemText(0, _translate("MainWindow", "RolesDefault"))
        self.RolesFind_Account_comboBox.setItemText(1, _translate("MainWindow", "Student"))
        self.RolesFind_Account_comboBox.setItemText(2, _translate("MainWindow", "Manager"))
        self.Search_Account_LineEdit.setPlaceholderText(_translate("MainWindow", "Search AccountID/Name..."))
        self.AccountInfo_Header.setText(_translate("MainWindow", "Account Info"))
        self.Add_Account_Button.setText(_translate("MainWindow", "Add Account"))
        item = self.Table_history.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "STT"))
        item = self.Table_history.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tên Đăng Nhập"))
        item = self.Table_history.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Thời gian đăng nhập"))
        item = self.Table_history.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Thành công"))
        self.hienthi_history.setText(_translate("MainWindow", "Hiển thị lịch sử"))
        self.label_8.setText(_translate("MainWindow", "ID Student"))
        self.label_9.setText(_translate("MainWindow", "Full Name"))
        self.label_13.setText(_translate("MainWindow", "Gender"))
        self.Gender_FaceReg_Student_comboBox.setItemText(0, _translate("MainWindow", "Male"))
        self.Gender_FaceReg_Student_comboBox.setItemText(1, _translate("MainWindow", "Female"))
        self.label_14.setText(_translate("MainWindow", "Date of Birth"))
        self.label_15.setText(_translate("MainWindow", "Phone Number"))
        self.label_16.setText(_translate("MainWindow", "Email"))
        self.label_17.setText(_translate("MainWindow", "Address"))
        self.OpenCamera.setText(_translate("MainWindow", "Open Camera"))
        self.CloseCamera.setText(_translate("MainWindow", "Close Camera"))
        self.attendance_type_combo.setItemText(0, _translate("MainWindow", "In"))
        self.attendance_type_combo.setItemText(1, _translate("MainWindow", "Out"))
        self.groupBox_dau.setTitle(_translate("MainWindow", "Thông tin tìm kiếm"))
        self.nhapmsv_2.setPlaceholderText(_translate("MainWindow", "Nhập mã số sinh viên..."))
        self.label_EnExHistoryEnd.setText(_translate("MainWindow", "Ngày kết thúc:"))
        self.label_nhapmsv_6.setText(_translate("MainWindow", "Nhập MSSV:"))
        self.label_EnExHistoryStart.setText(_translate("MainWindow", "Ngày bắt đầu:"))
        self.Find_EnExHistory_Button.setText(_translate("MainWindow", "Lọc"))
        self.Export_PDF_Button.setText(_translate("MainWindow", "Export to PDF"))
        item = self.EnExHistory_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "STT"))
        item = self.EnExHistory_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "MaSinhVien"))
        item = self.EnExHistory_Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ten"))
        item = self.EnExHistory_Table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "TrangThai"))
        item = self.EnExHistory_Table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "ThoiGianVao"))
        item = self.EnExHistory_Table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "ThoiGianRa"))
        self.label_fromdayp7.setText(_translate("MainWindow", "Từ ngày "))
        self.bt_taothongke.setText(_translate("MainWindow", "Tạo thống kê"))
        self.comboBoxpage_7.setItemText(0, _translate("MainWindow", "Tần suất ra vào theo tuần"))
        self.comboBoxpage_7.setItemText(1, _translate("MainWindow", "Tần suất ra vào theo ngày"))
        self.comboBoxpage_7.setItemText(2, _translate("MainWindow", "Tần suất ra vào theo tháng"))
        self.comboBoxpage_7.setItemText(3, _translate("MainWindow", "Giờ cao điểm ra vào thư viện"))
        self.comboBoxpage_7.setItemText(4, _translate("MainWindow", "Top sinh viên vào thư viện theo tuần"))
        self.comboBoxpage_7.setItemText(5, _translate("MainWindow", "Top người dùng đăng nhập"))
        self.bt_hienthibd.setText(_translate("MainWindow", "Hiển thị biểu đồ"))
        self.label_todayp7.setText(_translate("MainWindow", "Đến ngày"))
        self.label_12.setText(_translate("MainWindow", "Settings"))
        self.label.setText(_translate("MainWindow", "INDUSTRIAL\n"
"UNIVERSITY OF\n"
"HOCHIMINH CITY"))
        self.Student_2.setText(_translate("MainWindow", " Manage Student"))
        self.Accounts_2.setText(_translate("MainWindow", "Manage Account"))
        self.Account.setText(_translate("MainWindow", "Account"))
        self.LogHistory.setText(_translate("MainWindow", "Login history"))
        self.FaceReg_2.setText(_translate("MainWindow", "Facial recognition"))
        self.EnExHistory_2.setText(_translate("MainWindow", "Entry and exit history"))
        self.Statistics_2.setText(_translate("MainWindow", "Statistics"))
        self.Settings_2.setText(_translate("MainWindow", "Settings"))
        self.SignOut_2.setText(_translate("MainWindow", "Sign Out"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
