# Form implementation generated from reading ui file 'Update_AccountDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QDate, pyqtSignal
from PyQt6.QtWidgets import  QDialog,QMessageBox
import datetime
import re
from DAO_ManageAccount import DAO_Account
from database_connection import DatabaseConnection

class Ui_Update_Account_Dialog(object):
    def setupUi(self, Update_Account_Dialog):
        Update_Account_Dialog.setObjectName("Update_Account_Dialog")
        Update_Account_Dialog.resize(550, 820)
        Update_Account_Dialog.setStyleSheet("QDialog{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit{\n"
"    border: 1px solid gray;\n"
"    border-radius:6px;\n"
"    padding-left:15px;\n"
"    height:30px;\n"
"}\n"
"QDateEdit{\n"
"    border:1px solid gray;\n"
"    border-radius:6px;\n"
"    padding-left:15px;\n"
"    height:28px;\n"
"}\n"
"QComboBox{\n"
"    border:2px solid white;\n"
"    border-radius:8px;\n"
"    padding:1px 15px 1px 3px;\n"
"    background-color: black;\n"
"    color:white;\n"
"    height:25px;\n"
"    padding-left:15px;\n"
"    font-weight:bold;\n"
"    selection-background-color:#298089;\n"
"}\n"
"")
        self.line = QtWidgets.QFrame(parent=Update_Account_Dialog)
        self.line.setGeometry(QtCore.QRect(0, 50, 551, 31))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(parent=Update_Account_Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(parent=Update_Account_Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(230, 760, 301, 43))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Update_Account_Button = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.Update_Account_Button.setMinimumSize(QtCore.QSize(0, 41))
        self.Update_Account_Button.setStyleSheet("QPushButton{    \n"
"    background-color: #34D381;\n"
"    border:none;\n"
"    color:white;\n"
"    border-radius:8px;\n"
"    font-weight:bold;\n"
"    font-size:15px;\n"
"}")
        self.Update_Account_Button.setObjectName("Update_Account_Button")
        self.horizontalLayout_2.addWidget(self.Update_Account_Button)
        self.CancelButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.CancelButton.setMinimumSize(QtCore.QSize(0, 41))
        self.CancelButton.setStyleSheet("QPushButton{\n"
"    background-color: #585858;\n"
"    border:none;\n"
"    color:white;\n"
"    border-radius:8px;\n"
"    font-weight:bold;\n"
"    font-size:15px;\n"
"}")
        self.CancelButton.setObjectName("CancelButton")
        self.horizontalLayout_2.addWidget(self.CancelButton)
        self.layoutWidget_2 = QtWidgets.QWidget(parent=Update_Account_Dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 260, 511, 71))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.Update_Username_Account_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget_2)
        self.Update_Username_Account_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.Update_Username_Account_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Update_Username_Account_lineEdit.setFont(font)
        self.Update_Username_Account_lineEdit.setObjectName("Update_Username_Account_lineEdit")
        self.verticalLayout_2.addWidget(self.Update_Username_Account_lineEdit)
        self.layoutWidget_3 = QtWidgets.QWidget(parent=Update_Account_Dialog)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 340, 511, 71))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.Update_Password_Account_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget_3)
        self.Update_Password_Account_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.Update_Password_Account_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Update_Password_Account_lineEdit.setFont(font)
        self.Update_Password_Account_lineEdit.setObjectName("Update_Password_Account_lineEdit")
        self.verticalLayout_4.addWidget(self.Update_Password_Account_lineEdit)
        self.layoutWidget1 = QtWidgets.QWidget(parent=Update_Account_Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(21, 92, 511, 71))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.Update_ID_Manager_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.Update_ID_Manager_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.Update_ID_Manager_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Update_ID_Manager_lineEdit.setFont(font)
        self.Update_ID_Manager_lineEdit.setObjectName("Update_ID_Manager_lineEdit")
        self.verticalLayout.addWidget(self.Update_ID_Manager_lineEdit)
        self.layoutWidget2 = QtWidgets.QWidget(parent=Update_Account_Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 170, 511, 71))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.Update_Name_Manager_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget2)
        self.Update_Name_Manager_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.Update_Name_Manager_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Update_Name_Manager_lineEdit.setFont(font)
        self.Update_Name_Manager_lineEdit.setObjectName("Update_Name_Manager_lineEdit")
        self.verticalLayout_3.addWidget(self.Update_Name_Manager_lineEdit)
        self.layoutWidget3 = QtWidgets.QWidget(parent=Update_Account_Dialog)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 590, 511, 71))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_10 = QtWidgets.QLabel(parent=self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_9.addWidget(self.label_10)
        self.Update_Email_Manager_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget3)
        self.Update_Email_Manager_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.Update_Email_Manager_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Update_Email_Manager_lineEdit.setFont(font)
        self.Update_Email_Manager_lineEdit.setObjectName("Update_Email_Manager_lineEdit")
        self.verticalLayout_9.addWidget(self.Update_Email_Manager_lineEdit)
        self.layoutWidget4 = QtWidgets.QWidget(parent=Update_Account_Dialog)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 670, 511, 71))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(parent=self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.Update_Address_Manager_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget4)
        self.Update_Address_Manager_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.Update_Address_Manager_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Update_Address_Manager_lineEdit.setFont(font)
        self.Update_Address_Manager_lineEdit.setObjectName("Update_Address_Manager_lineEdit")
        self.verticalLayout_5.addWidget(self.Update_Address_Manager_lineEdit)
        self.layoutWidget5 = QtWidgets.QWidget(parent=Update_Account_Dialog)
        self.layoutWidget5.setGeometry(QtCore.QRect(20, 510, 511, 71))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_9 = QtWidgets.QLabel(parent=self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9)
        self.Update_Phone_Manager_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget5)
        self.Update_Phone_Manager_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.Update_Phone_Manager_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Update_Phone_Manager_lineEdit.setFont(font)
        self.Update_Phone_Manager_lineEdit.setObjectName("Update_Phone_Manager_lineEdit")
        self.verticalLayout_8.addWidget(self.Update_Phone_Manager_lineEdit)
        self.layoutWidget6 = QtWidgets.QWidget(parent=Update_Account_Dialog)
        self.layoutWidget6.setGeometry(QtCore.QRect(20, 430, 511, 60))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(parent=self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.Update_Role_Account_comboBox = QtWidgets.QComboBox(parent=self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Update_Role_Account_comboBox.setFont(font)
        self.Update_Role_Account_comboBox.setObjectName("Update_Role_Account_comboBox")
        self.Update_Role_Account_comboBox.addItem("")
        self.Update_Role_Account_comboBox.addItem("")
        self.verticalLayout_6.addWidget(self.Update_Role_Account_comboBox)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_11 = QtWidgets.QLabel(parent=self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_10.addWidget(self.label_11)
        self.Update_Gender_Manager_comboBox = QtWidgets.QComboBox(parent=self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Update_Gender_Manager_comboBox.setFont(font)
        self.Update_Gender_Manager_comboBox.setObjectName("Update_Gender_Manager_comboBox")
        self.Update_Gender_Manager_comboBox.addItem("")
        self.Update_Gender_Manager_comboBox.addItem("")
        self.verticalLayout_10.addWidget(self.Update_Gender_Manager_comboBox)
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(parent=self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.Update_Birth_Manage_dateEdit = QtWidgets.QDateEdit(parent=self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Update_Birth_Manage_dateEdit.setFont(font)
        self.Update_Birth_Manage_dateEdit.setObjectName("Update_Birth_Manage_dateEdit")
        self.verticalLayout_7.addWidget(self.Update_Birth_Manage_dateEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_7)

        self.retranslateUi(Update_Account_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Update_Account_Dialog)

    def retranslateUi(self, Update_Account_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Update_Account_Dialog.setWindowTitle(_translate("Update_Account_Dialog", "Dialog"))
        self.label.setText(_translate("Update_Account_Dialog", "Update Account"))
        self.Update_Account_Button.setText(_translate("Update_Account_Dialog", "Update Account"))
        self.CancelButton.setText(_translate("Update_Account_Dialog", "Cancel"))
        self.label_3.setText(_translate("Update_Account_Dialog", "Username"))
        self.label_5.setText(_translate("Update_Account_Dialog", "Password"))
        self.label_2.setText(_translate("Update_Account_Dialog", "ID Manager"))
        self.label_4.setText(_translate("Update_Account_Dialog", "Full Name"))
        self.label_10.setText(_translate("Update_Account_Dialog", "Email"))
        self.label_6.setText(_translate("Update_Account_Dialog", "Address"))
        self.label_9.setText(_translate("Update_Account_Dialog", "Phone Number"))
        self.label_7.setText(_translate("Update_Account_Dialog", "Role"))
        self.Update_Role_Account_comboBox.setItemText(0, _translate("Update_Account_Dialog", "quanly"))
        self.Update_Role_Account_comboBox.setItemText(1, _translate("Update_Account_Dialog", "admin"))
        self.label_11.setText(_translate("Update_Account_Dialog", "Gender"))
        self.Update_Gender_Manager_comboBox.setItemText(0, _translate("Update_Account_Dialog", "Male"))
        self.Update_Gender_Manager_comboBox.setItemText(1, _translate("Update_Account_Dialog", "Female"))
        self.label_8.setText(_translate("Update_Account_Dialog", "Date of Birth"))


       
class UpdateAccountDialog(QDialog, Ui_Update_Account_Dialog):
        data_updated = pyqtSignal()
        def __init__(self, row_index, row_data, connection=None, parent=None):
                super().__init__(parent)
                self.setupUi(self)
                self.row_index = row_index
                self.row_data = row_data

                # Khởi tạo kết nối và DAO
                if not isinstance(connection, DatabaseConnection):
                        raise ValueError("Đối tượng kết nối phải là một DatabaseConnection.")
                self.db = connection
                self.dao_quan_ly = DAO_Account(self.db)
                
                # Lấy thông tin sinh viên
                self.account_info = self.select_account()
                
                if self.account_info:
                        self.populate_account_info()  # Gọi hàm để điền thông tin vào UI
                
                self.Update_Account_Button.clicked.connect(self.update_data)                
                self.CancelButton.clicked.connect(self.reject)

                self.patterns = {
                'user_id': r'^\d{6}$',  # Ví dụ: 12345678
                'ten': r'^([A-ZÀ-Ỹ][a-zà-ỹ]+)(?:\s[A-ZÀ-Ỹ][a-zà-ỹ]+)*$',  # Ví dụ: Nguyễn Văn A
                'email': r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$',  # Ví dụ: email@example.com
                'sdt': r'^0\d{9}$',  # Ví dụ: 0123456789
                'dia_chi': r'^[A-Za-z0-9À-ỹ\s,.-/]{5,100}$r',  # Ví dụ: 123 Đường ABC                        
                'username': r'^\S{6,}$',   # Không chứa khoảng trắng, lớn hơn 5 ký tự
                'password': r'^.{5,20}$'        
                }
                
        def select_account(self):
                self.cursor = self.db.get_cursor()
                
                self.user_id = self.row_data[0]
                
                # Sửa câu truy vấn
                select_query = """SELECT user_id, name, gender, username, password, role, birthday, email, phone, address FROM users 
                                WHERE user_id = ?"""  # Thay thế ? bằng %s hoặc ? tùy vào driver của bạn
                
                self.cursor.execute(select_query, (self.user_id,))
                records = self.cursor.fetchall()

                return records[0] if records else None  # Trả về bản ghi đầu tiên hoặc None nếu không có

        def populate_account_info(self):
                self.Update_ID_Manager_lineEdit.setText(self.account_info[0])  # Mã sinh viên
                self.Update_Name_Manager_lineEdit.setText(self.account_info[1])  # Tên sinh viên
                self.Update_Gender_Manager_comboBox.setCurrentText(self.account_info[2])  # Giới tính
                self.Update_Username_Account_lineEdit.setText(self.account_info[3])  # Tên sinh viên
                self.Update_Password_Account_lineEdit.setText(self.account_info[4])  # Tên sinh viên
                self.Update_Role_Account_comboBox.setCurrentText(self.account_info[5])  # Giới tính
                
                # Ngày sinh
                if isinstance(self.account_info[6], datetime.date):  # Kiểm tra nếu là đối tượng datetime.date
                        q_date = QDate(self.account_info[6].year, self.account_info[6].month, self.account_info[6].day)
                        self.Update_Birth_Manage_dateEdit.setDate(q_date)
                
                # Điền thêm các thông tin khác
                self.Update_Email_Manager_lineEdit.setText(self.account_info[7])  # Email
                self.Update_Phone_Manager_lineEdit.setText(self.account_info[8])  # Số điện thoại                
                self.Update_Address_Manager_lineEdit.setText(self.account_info[9])  # Địa chỉ

        def update_data(self):
        # Lấy thông tin từ các trường nhập
                ma_id = self.Update_ID_Manager_lineEdit.text()
                ten = self.Update_Name_Manager_lineEdit.text()
                username = self.Update_Username_Account_lineEdit.text()
                password = self.Update_Password_Account_lineEdit.text()
                role = self.Update_Role_Account_comboBox.currentText()
                gioi_tinh = self.Update_Gender_Manager_comboBox.currentText()
                ngay_sinh = self.Update_Birth_Manage_dateEdit.date().toString("yyyy-MM-dd")
                email = self.Update_Email_Manager_lineEdit.text()
                sdt = self.Update_Phone_Manager_lineEdit.text()                
                dia_chi = self.Update_Address_Manager_lineEdit.text()

                if not ma_id or not ten or not username or not password:
                        QMessageBox.warning(self, "Lỗi nhập liệu", "Mã Quản lí, tên, Username và password không được để trống!")
                        return

                        # Kiểm tra định dạng các trường bắt buộc
                if not re.match(self.patterns['user_id'], ma_id):
                        QMessageBox.warning(self, "Lỗi nhập liệu", "Mã Quản lí không hợp lệ! (Phải gồm 6 số, ví dụ: 123456)")
                        return

                if not re.match(self.patterns['ten'], ten):
                        QMessageBox.warning(self, "Lỗi nhập liệu", "Tên Quản lí không hợp lệ! (Ví dụ: Nguyễn Văn An)")
                        return

                if not re.match(self.patterns['username'], username):
                        QMessageBox.warning(self, "Lỗi nhập liệu", "Username không hợp lệ! Username nhiều hơn 5 kí tự (Ví dụ: email@example.com)")
                        return
                
                if not re.match(self.patterns['password'], password):
                        QMessageBox.warning(self, "Lỗi nhập liệu", "Password không hợp lệ! Password Từ 5-20 kí tự (Ví dụ: email@example.com)")
                        return
                
                # Kiểm tra các trường tùy chọn nếu người dùng nhập liệu
                if email and not re.match(self.patterns['email'], email):
                        QMessageBox.warning(self, "Lỗi nhập liệu", "Email không hợp lệ! (Ví dụ: email@example.com)")
                        return

                if sdt and not re.match(self.patterns['sdt'], sdt):
                        QMessageBox.warning(self, "Lỗi nhập liệu", "Số điện thoại không hợp lệ! (Phải có 10 chữ số, ví dụ: 0123456789)")
                        return

                if dia_chi and not re.match(self.patterns['dia_chi'], dia_chi):
                        QMessageBox.warning(self, "Lỗi nhập liệu", "Địa chỉ không hợp lệ! (Chỉ gồm chữ và số, từ 5 đến 100 ký tự)")
                        return

                try:
                        if self.dao_quan_ly.cap_nhat_Account(ma_id, ten, username, password, role, gioi_tinh, ngay_sinh, email, sdt, dia_chi):
                                QMessageBox.information(self, "Thành công", "Tài khoản Quản lí đã được cập nhật thành công!")
                                self.data_updated.emit()
                                self.accept()  # Đóng hộp thoại nếu thêm thành công
                        else:
                                QMessageBox.warning(self, "Lỗi", "Mã Quản lí đã tồn tại! Vui lòng nhập mã khác.")
                except Exception as e:
                        print(f"Lỗi khi cập nhật tài khoản: {e}")
                        QMessageBox.critical(self, "Lỗi cơ sở dữ liệu", "Đã xảy ra lỗi khi cập nhật Quản lí. Vui lòng thử lại!")

                
        