# Form implementation generated from reading ui file 'UpdateStudentDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QDate, pyqtSignal
from PyQt6.QtWidgets import  QDialog,QMessageBox
import datetime
import re
from SaveImg import UI_SaveImg
from DAO_QLSV import DAO_SinhVien
from database_connection import DatabaseConnection

class Ui_Update_StudentDialog(object):
                
    def setupUi(self, Update_StudentDialog):
        Update_StudentDialog.setObjectName("Update_StudentDialog")
        Update_StudentDialog.resize(550, 620)
        Update_StudentDialog.setStyleSheet("QDialog{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit{\n"
"    border: 1px solid gray;\n"
"    border-radius:6px;\n"
"    padding-left:15px;\n"
"    height:30px;\n"
"}\n"
"QDateEdit{\n"
"    border:1px solid gray;\n"
"    border-radius:6px;\n"
"    padding-left:15px;\n"
"    height:28px;\n"
"}\n"
"QComboBox{\n"
"    border:2px solid white;\n"
"    border-radius:8px;\n"
"    padding:1px 15px 1px 3px;\n"
"    background-color: black;\n"
"    color:white;\n"
"    height:25px;\n"
"    padding-left:15px;\n"
"    font-weight:bold;\n"
"    selection-background-color:#298089;\n"
"}\n"
"")
        self.line = QtWidgets.QFrame(parent=Update_StudentDialog)
        self.line.setGeometry(QtCore.QRect(0, 50, 551, 31))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(parent=Update_StudentDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(parent=Update_StudentDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 91, 511, 451))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.Update_ID_Student_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.Update_ID_Student_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.Update_ID_Student_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Update_ID_Student_lineEdit.setFont(font)
        self.Update_ID_Student_lineEdit.setObjectName("Update_ID_Student_lineEdit")
        self.verticalLayout.addWidget(self.Update_ID_Student_lineEdit)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.Update_Name_Student_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.Update_Name_Student_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.Update_Name_Student_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Update_Name_Student_lineEdit.setFont(font)
        self.Update_Name_Student_lineEdit.setObjectName("Update_Name_Student_lineEdit")
        self.verticalLayout_3.addWidget(self.Update_Name_Student_lineEdit)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.Update_Gender_Student_comboBox = QtWidgets.QComboBox(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Update_Gender_Student_comboBox.setFont(font)
        self.Update_Gender_Student_comboBox.setObjectName("Update_Gender_Student_comboBox")
        self.Update_Gender_Student_comboBox.addItem("")
        self.Update_Gender_Student_comboBox.addItem("")
        self.verticalLayout_6.addWidget(self.Update_Gender_Student_comboBox)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.Update_Birth_Student_dateEdit = QtWidgets.QDateEdit(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Update_Birth_Student_dateEdit.setFont(font)
        self.Update_Birth_Student_dateEdit.setObjectName("Update_Birth_Student_dateEdit")
        self.verticalLayout_7.addWidget(self.Update_Birth_Student_dateEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_9 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9)
        self.Update_Phone_Student_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.Update_Phone_Student_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.Update_Phone_Student_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Update_Phone_Student_lineEdit.setFont(font)
        self.Update_Phone_Student_lineEdit.setObjectName("Update_Phone_Student_lineEdit")
        self.verticalLayout_8.addWidget(self.Update_Phone_Student_lineEdit)
        self.verticalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_10 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_9.addWidget(self.label_10)
        self.Update_Email_Student_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.Update_Email_Student_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.Update_Email_Student_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Update_Email_Student_lineEdit.setFont(font)
        self.Update_Email_Student_lineEdit.setObjectName("Update_Email_Student_lineEdit")
        self.verticalLayout_9.addWidget(self.Update_Email_Student_lineEdit)
        self.verticalLayout_2.addLayout(self.verticalLayout_9)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.Update_Address_Student_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.Update_Address_Student_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.Update_Address_Student_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Update_Address_Student_lineEdit.setFont(font)
        self.Update_Address_Student_lineEdit.setObjectName("Update_Address_Student_lineEdit")
        self.verticalLayout_5.addWidget(self.Update_Address_Student_lineEdit)
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        self.layoutWidget1 = QtWidgets.QWidget(parent=Update_StudentDialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(201, 560, 321, 43))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Update_Student_Button = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.Update_Student_Button.setMinimumSize(QtCore.QSize(130, 41))
        self.Update_Student_Button.setStyleSheet("QPushButton{    \n"
"    background-color: #34D381;\n"
"    border:none;\n"
"    color:white;\n"
"    border-radius:8px;\n"
"    font-weight:bold;\n"
"    font-size:15px;\n"
"}")
        self.Update_Student_Button.setObjectName("Update_Student_Button")
        self.horizontalLayout_2.addWidget(self.Update_Student_Button)
        self.Update_SaveImage_Student_Button = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.Update_SaveImage_Student_Button.setMinimumSize(QtCore.QSize(0, 41))
        self.Update_SaveImage_Student_Button.setStyleSheet("QPushButton{    \n"
"    background-color: rgb(255, 85, 0);\n"
"    border:none;\n"
"    color:white;\n"
"    border-radius:8px;\n"
"    font-weight:bold;\n"
"    font-size:15px;\n"
"}")
        self.Update_SaveImage_Student_Button.setObjectName("Update_SaveImage_Student_Button")
        self.horizontalLayout_2.addWidget(self.Update_SaveImage_Student_Button)
        self.Update_CancelButton = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.Update_CancelButton.setMinimumSize(QtCore.QSize(0, 41))
        self.Update_CancelButton.setStyleSheet("QPushButton{\n"
"    background-color: #585858;\n"
"    border:none;\n"
"    color:white;\n"
"    border-radius:8px;\n"
"    font-weight:bold;\n"
"    font-size:15px;\n"
"}")
        self.Update_CancelButton.setObjectName("Update_CancelButton")
        self.horizontalLayout_2.addWidget(self.Update_CancelButton)

        self.retranslateUi(Update_StudentDialog)
        QtCore.QMetaObject.connectSlotsByName(Update_StudentDialog)

    def retranslateUi(self, Update_StudentDialog):
        _translate = QtCore.QCoreApplication.translate
        Update_StudentDialog.setWindowTitle(_translate("Update_StudentDialog", "Dialog"))
        self.label.setText(_translate("Update_StudentDialog", "Student Information"))
        self.label_2.setText(_translate("Update_StudentDialog", "ID Student"))
        self.label_4.setText(_translate("Update_StudentDialog", "Full Name"))
        self.label_7.setText(_translate("Update_StudentDialog", "Gender"))
        self.Update_Gender_Student_comboBox.setItemText(0, _translate("Update_StudentDialog", "Male"))
        self.Update_Gender_Student_comboBox.setItemText(1, _translate("Update_StudentDialog", "Female"))
        self.label_8.setText(_translate("Update_StudentDialog", "Date of Birth"))
        self.label_9.setText(_translate("Update_StudentDialog", "Phone Number"))
        self.label_10.setText(_translate("Update_StudentDialog", "Email"))
        self.label_6.setText(_translate("Update_StudentDialog", "Address"))
        self.Update_Student_Button.setText(_translate("Update_StudentDialog", "Update Student"))
        self.Update_SaveImage_Student_Button.setText(_translate("Update_StudentDialog", "Save Image"))
        self.Update_CancelButton.setText(_translate("Update_StudentDialog", "Cancel"))
        
        
class UpdateStudentDialog(QDialog, Ui_Update_StudentDialog):
        data_updated = pyqtSignal()
        def __init__(self, row_index, row_data, connection=None, parent=None):
                super().__init__(parent)
                self.setupUi(self)
                self.row_index = row_index
                self.row_data = row_data

                # Khởi tạo kết nối và DAO
                if not isinstance(connection, DatabaseConnection):
                        raise ValueError("Đối tượng kết nối phải là một DatabaseConnection.")
                self.db = connection
                self.dao_sinh_vien = DAO_SinhVien(self.db)
                
                # Lấy thông tin sinh viên
                self.student_info = self.select_student()
                
                if self.student_info:
                        self.populate_student_info()  # Gọi hàm để điền thông tin vào UI
                
                self.Update_Student_Button.clicked.connect(self.update_data)
                self.Update_SaveImage_Student_Button.clicked.connect(self.open_SaveImg_dialog)
                
                self.Update_CancelButton.clicked.connect(self.reject)
                
                self.patterns = {
                'ma_sv': r'^\d{8}$',  # Ví dụ: 12345678
                'ten': r'^([A-ZÀ-Ỹ][a-zà-ỹ]+)(?:\s[A-ZÀ-Ỹ][a-zà-ỹ]+)*$',  # Ví dụ: Nguyễn Văn A
                'email': r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$',  # Ví dụ: email@example.com
                'sdt': r'^0\d{9}$',  # Ví dụ: 0123456789
                'dia_chi': r'^[A-Za-z0-9À-ỹ\s,.-/]{5,100}$r'  # Ví dụ: 123 Đường ABC
                }

        def select_student(self):
                self.cursor = self.db.get_cursor()
                
                self.student_id = self.row_data[0]
                
                # Sửa câu truy vấn
                select_query = """SELECT ma_sv, ten, gioi_tinh, ngay_sinh, sdt, email, dia_chi 
                                FROM students 
                                WHERE ma_sv = ?"""  # Thay thế ? bằng %s hoặc ? tùy vào driver của bạn
                
                self.cursor.execute(select_query, (self.student_id,))
                records = self.cursor.fetchall()

                return records[0] if records else None  # Trả về bản ghi đầu tiên hoặc None nếu không có

        def populate_student_info(self):
                self.Update_ID_Student_lineEdit.setText(self.student_info[0])  # Mã sinh viên
                self.Update_Name_Student_lineEdit.setText(self.student_info[1])  # Tên sinh viên
                self.Update_Gender_Student_comboBox.setCurrentText(self.student_info[2])  # Giới tính

                # Ngày sinh
                if isinstance(self.student_info[3], datetime.date):  # Kiểm tra nếu là đối tượng datetime.date
                        q_date = QDate(self.student_info[3].year, self.student_info[3].month, self.student_info[3].day)
                        self.Update_Birth_Student_dateEdit.setDate(q_date)
                
                # Điền thêm các thông tin khác
                self.Update_Phone_Student_lineEdit.setText(self.student_info[4])  # Số điện thoại
                self.Update_Email_Student_lineEdit.setText(self.student_info[5])  # Email
                self.Update_Address_Student_lineEdit.setText(self.student_info[6])  # Địa chỉ
        def open_SaveImg_dialog(self):
                save_img_ui = UI_SaveImg()  # Giả định bạn đã định nghĩa class UI_SaveImg
                result = save_img_ui.exec()
                if result == QDialog.DialogCode.Accepted:  # Chắc chắn so sánh với QDialog.Accepted
                        pass
        def update_data(self):
        # Lấy thông tin từ các trường nhập
                ma_sv = self.Update_ID_Student_lineEdit.text()
                ten = self.Update_Name_Student_lineEdit.text()
                gioi_tinh = self.Update_Gender_Student_comboBox.currentText()
                ngay_sinh = self.Update_Birth_Student_dateEdit.date().toString("yyyy-MM-dd")
                sdt = self.Update_Phone_Student_lineEdit.text()
                email = self.Update_Email_Student_lineEdit.text()
                dia_chi = self.Update_Address_Student_lineEdit.text()

                if not ma_sv or not ten:
                        QMessageBox.warning(self, "Lỗi nhập liệu", "Mã sinh viên và tên không được để trống!")
                        return

                        # Kiểm tra định dạng các trường bắt buộc
                if not re.match(self.patterns['ma_sv'], ma_sv):
                        QMessageBox.warning(self, "Lỗi nhập liệu", "Mã sinh viên không hợp lệ! (Phải gồm 8 số, ví dụ: 12345678)")
                        return

                if not re.match(self.patterns['ten'], ten):
                        QMessageBox.warning(self, "Lỗi nhập liệu", "Tên sinh viên không hợp lệ! (Ví dụ: Nguyễn Văn An)")
                        return

                        # Kiểm tra các trường tùy chọn nếu người dùng nhập liệu
                if email and not re.match(self.patterns['email'], email):
                        QMessageBox.warning(self, "Lỗi nhập liệu", "Email không hợp lệ! (Ví dụ: email@example.com)")
                        return

                if sdt and not re.match(self.patterns['sdt'], sdt):
                        QMessageBox.warning(self, "Lỗi nhập liệu", "Số điện thoại không hợp lệ! (Phải có 10 chữ số, ví dụ: 0123456789)")
                        return

                if dia_chi and not re.match(self.patterns['dia_chi'], dia_chi):
                        QMessageBox.warning(self, "Lỗi nhập liệu", "Địa chỉ không hợp lệ! (Chỉ gồm chữ và số, từ 5 đến 100 ký tự)")
                        return

                        # Thêm sinh viên vào cơ sở dữ liệu
                try:
                        if self.dao_sinh_vien.cap_nhat_sinh_vien(ma_sv, ten, gioi_tinh, ngay_sinh, sdt, email, dia_chi):
                                QMessageBox.information(self, "Thành công", "Sinh viên đã được cập nhật thành công!")
                                self.data_updated.emit()
                                self.accept()  # Đóng hộp thoại nếu thêm thành công
                except Exception as e:
                        print(f"Lỗi khi thêm sinh viên: {e}")
                        QMessageBox.critical(self, "Lỗi cơ sở dữ liệu", "Đã xảy ra lỗi khi cập nhật sinh viên. Vui lòng thử lại!")
 
                
        